BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Skins" (
	"CSGOStash_ID"	INTEGER,
	"Weapon"	TEXT,
	"Name"	TEXT,
	"Rarity"	TEXT,
	"Collection"	TEXT,
	PRIMARY KEY("CSGOStash_ID")
);
CREATE TABLE IF NOT EXISTS "Conditions" (
	"condition_id"	INTEGER,
	"condition"	TEXT,
	PRIMARY KEY("condition_id")
);
CREATE TABLE IF NOT EXISTS "Prices" (
	"Skin_ID"	INTEGER,
	"Condition_ID"	INTEGER,
	"Steam_Price"	NUMERIC,
	"Bitskin_Price"	NUMERIC,
	PRIMARY KEY("Skin_ID","Condition_ID")
);
INSERT INTO "Skins" ("CSGOStash_ID","Weapon","Name","Rarity","Collection") VALUES (7,'UMP-45','Caramel','Consumer','The Assault Collection'),
 (8,'AUG','Hot Rod','Mil-Spec','The Assault Collection'),
 (9,'Glock-18','Fade','Restricted','The Assault Collection'),
 (13,'MP9','Bulldozer','Restricted','The Assault Collection'),
 (14,'SG 553','Tornado','Consumer','The Assault Collection'),
 (15,'Negev','Anodized Navy','Mil-Spec','The Assault Collection'),
 (16,'Five-SeveN','Candy Apple','Industrial','The Assault Collection'),
 (17,'FAMAS','Contrast Spray','Consumer','The Office Collection'),
 (18,'M249','Blizzard Marbleized','Industrial','The Office Collection'),
 (19,'MP7','Whiteout','Mil-Spec','The Office Collection'),
 (20,'P2000','Silver','Mil-Spec','The Office Collection'),
 (21,'G3SG1','Arctic Camo','Industrial','The Office Collection'),
 (22,'Galil AR','Winter Forest','Industrial','The Office Collection'),
 (23,'XM1014','Fallout Warning','Industrial','The Nuke Collection'),
 (24,'M4A4','Radiation Hazard','Mil-Spec','The Nuke Collection'),
 (25,'UMP-45','Fallout Warning','Industrial','The Nuke Collection'),
 (26,'PP-Bizon','Irradiated Alert','Consumer','The Nuke Collection'),
 (27,'P90','Fallout Warning','Industrial','The Nuke Collection'),
 (28,'Tec-9','Nuclear Threat','Restricted','The Nuke Collection'),
 (29,'P250','Nuclear Threat','Restricted','The Nuke Collection'),
 (30,'Sawed-Off','Irradiated Alert','Consumer','The Nuke Collection'),
 (31,'MAG-7','Irradiated Alert','Consumer','The Nuke Collection'),
 (32,'SCAR-20','Splash Jam','Classified','The Militia Collection'),
 (33,'Nova','Modern Hunter','Mil-Spec','The Militia Collection'),
 (34,'PP-Bizon','Forest Leaves','Consumer','The Militia Collection'),
 (35,'PP-Bizon','Modern Hunter','Mil-Spec','The Militia Collection'),
 (36,'XM1014','Blaze Orange','Mil-Spec','The Militia Collection'),
 (37,'P250','Modern Hunter','Mil-Spec','The Militia Collection'),
 (38,'MAC-10','Tornado','Consumer','The Militia Collection'),
 (39,'Nova','Blaze Orange','Mil-Spec','The Militia Collection'),
 (40,'XM1014','Grassland','Consumer','The Militia Collection'),
 (41,'P2000','Grassland Leaves','Industrial','The Militia Collection'),
 (42,'M4A4','Modern Hunter','Restricted','The Militia Collection'),
 (43,'Nova','Walnut','Consumer','The Inferno Collection'),
 (44,'M4A4','Tornado','Industrial','The Inferno Collection'),
 (45,'Tec-9','Brass','Mil-Spec','The Inferno Collection'),
 (46,'P250','Gunsmoke','Industrial','The Inferno Collection'),
 (47,'Dual Berettas','Anodized Navy','Mil-Spec','The Inferno Collection'),
 (48,'MAG-7','Sand Dune','Consumer','The Inferno Collection'),
 (49,'AK-47','Black Laminate','Mil-Spec','The Vertigo Collection'),
 (50,'PP-Bizon','Carbon Fiber','Industrial','The Vertigo Collection'),
 (51,'MAC-10','Urban DDPAT','Consumer','The Vertigo Collection'),
 (52,'P90','Glacier Mesh','Mil-Spec','The Vertigo Collection'),
 (53,'Dual Berettas','Demolition','Restricted','The Vertigo Collection'),
 (54,'XM1014','Urban Perforated','Consumer','The Vertigo Collection'),
 (55,'M4A4','Jungle Tiger','Industrial','The Aztec Collection'),
 (56,'SSG 08','Lichen Dashed','Consumer','The Aztec Collection'),
 (57,'Five-SeveN','Jungle','Consumer','The Aztec Collection'),
 (58,'Tec-9','Ossified','Mil-Spec','The Aztec Collection'),
 (59,'Nova','Forest Leaves','Consumer','The Aztec Collection'),
 (60,'AK-47','Jungle Spray','Industrial','The Aztec Collection'),
 (61,'AK-47','Predator','Industrial','The Dust Collection'),
 (62,'SCAR-20','Palm','Industrial','The Dust Collection'),
 (63,'Sawed-Off','Copper','Mil-Spec','The Dust Collection'),
 (64,'M4A4','Desert Storm','Industrial','The Dust Collection'),
 (65,'AUG','Copperhead','Mil-Spec','The Dust Collection'),
 (66,'Glock-18','Brass','Restricted','The Dust Collection'),
 (67,'P2000','Scorpion','Restricted','The Dust Collection'),
 (68,'Desert Eagle','Blaze','Restricted','The Dust Collection'),
 (69,'AWP','Snake Camo','Mil-Spec','The Dust Collection'),
 (70,'P90','Death by Kitty','Covert','The eSports 2013 Collection'),
 (71,'AWP','BOOM','Classified','The eSports 2013 Collection'),
 (72,'MAG-7','Memento','Mil-Spec','The eSports 2013 Collection'),
 (73,'Galil AR','Orange DDPAT','Restricted','The eSports 2013 Collection'),
 (74,'FAMAS','Doomkitty','Mil-Spec','The eSports 2013 Collection'),
 (75,'P250','Splash','Restricted','The eSports 2013 Collection'),
 (76,'Sawed-Off','Orange DDPAT','Restricted','The eSports 2013 Collection'),
 (77,'M4A4','Faded Zebra','Mil-Spec','The eSports 2013 Collection'),
 (78,'AK-47','Red Laminate','Classified','The eSports 2013 Collection'),
 (79,'AWP','Lightning Strike','Covert','The Arms Deal Collection'),
 (80,'AUG','Wings','Mil-Spec','The Arms Deal Collection'),
 (81,'SG 553','Ultraviolet','Mil-Spec','The Arms Deal Collection'),
 (82,'AK-47','Case Hardened','Classified','The Arms Deal Collection'),
 (83,'Desert Eagle','Hypnotic','Classified','The Arms Deal Collection'),
 (84,'Glock-18','Dragon Tattoo','Restricted','The Arms Deal Collection'),
 (85,'USP-S','Dark Water','Restricted','The Arms Deal Collection'),
 (86,'MP7','Skulls','Mil-Spec','The Arms Deal Collection'),
 (87,'M4A1-S','Dark Water','Restricted','The Arms Deal Collection'),
 (93,'SCAR-20','Emerald','Restricted','The Alpha Collection'),
 (94,'MP7','Groundwater','Consumer','The Alpha Collection'),
 (95,'AUG','Anodized Navy','Mil-Spec','The Alpha Collection'),
 (96,'FAMAS','Spitfire','Restricted','The Alpha Collection'),
 (97,'PP-Bizon','Rust Coat','Mil-Spec','The Alpha Collection'),
 (98,'XM1014','Jungle','Consumer','The Alpha Collection'),
 (99,'Five-SeveN','Anodized Gunmetal','Consumer','The Alpha Collection'),
 (101,'MP9','Dry Season','Consumer','The Alpha Collection'),
 (102,'Sawed-Off','Mosaico','Industrial','The Alpha Collection'),
 (103,'MAG-7','Hazard','Mil-Spec','The Alpha Collection'),
 (104,'Negev','Palm','Industrial','The Alpha Collection'),
 (105,'Tec-9','Tornado','Consumer','The Alpha Collection'),
 (106,'M249','Jungle DDPAT','Consumer','The Alpha Collection'),
 (107,'SSG 08','Mayan Dreams','Industrial','The Alpha Collection'),
 (108,'Glock-18','Sand Dune','Industrial','The Alpha Collection'),
 (109,'USP-S','Overgrowth','Restricted','The Bravo Collection'),
 (110,'AWP','Graphite','Classified','The Bravo Collection'),
 (111,'G3SG1','Demeter','Mil-Spec','The Bravo Collection'),
 (112,'Galil AR','Shattered','Mil-Spec','The Bravo Collection'),
 (113,'SG 553','Wave Spray','Mil-Spec','The Bravo Collection'),
 (114,'AK-47','Fire Serpent','Covert','The Bravo Collection'),
 (115,'UMP-45','Bone Pile','Mil-Spec','The Bravo Collection'),
 (116,'MAC-10','Graven','Restricted','The Bravo Collection'),
 (117,'P2000','Ocean Foam','Classified','The Bravo Collection'),
 (118,'Dual Berettas','Black Limba','Mil-Spec','The Bravo Collection'),
 (119,'M4A4','Zirka','Restricted','The Bravo Collection'),
 (120,'Desert Eagle','Golden Koi','Covert','The Bravo Collection'),
 (121,'P90','Emerald Dragon','Classified','The Bravo Collection'),
 (122,'Nova','Tempest','Mil-Spec','The Bravo Collection'),
 (123,'M4A1-S','Bright Water','Restricted','The Bravo Collection'),
 (124,'SSG 08','Blood in the Water','Covert','The Arms Deal 2 Collection'),
 (125,'USP-S','Serum','Classified','The Arms Deal 2 Collection'),
 (126,'M4A1-S','Blood Tiger','Mil-Spec','The Arms Deal 2 Collection'),
 (127,'MP9','Hypnotic','Restricted','The Arms Deal 2 Collection'),
 (128,'P90','Cold Blooded','Classified','The Arms Deal 2 Collection'),
 (129,'Dual Berettas','Hemoglobin','Restricted','The Arms Deal 2 Collection'),
 (130,'P250','Hive','Mil-Spec','The Arms Deal 2 Collection'),
 (131,'Five-SeveN','Case Hardened','Restricted','The Arms Deal 2 Collection'),
 (132,'FAMAS','Hexane','Mil-Spec','The Arms Deal 2 Collection'),
 (133,'Tec-9','Blue Titanium','Mil-Spec','The Arms Deal 2 Collection'),
 (134,'Nova','Graphite','Restricted','The Arms Deal 2 Collection'),
 (135,'SCAR-20','Crimson Web','Mil-Spec','The Arms Deal 2 Collection'),
 (136,'G3SG1','Desert Storm','Consumer','The Dust 2 Collection'),
 (137,'P250','Sand Dune','Consumer','The Dust 2 Collection'),
 (138,'Sawed-Off','Snake Camo','Industrial','The Dust 2 Collection'),
 (139,'SG 553','Damascus Steel','Mil-Spec','The Dust 2 Collection'),
 (140,'AK-47','Safari Mesh','Industrial','The Dust 2 Collection'),
 (141,'SCAR-20','Sand Mesh','Consumer','The Dust 2 Collection'),
 (142,'Five-SeveN','Orange Peel','Industrial','The Dust 2 Collection'),
 (143,'P2000','Amber Fade','Restricted','The Dust 2 Collection'),
 (144,'P90','Sand Spray','Consumer','The Dust 2 Collection'),
 (145,'MP9','Sand Dashed','Consumer','The Dust 2 Collection'),
 (146,'PP-Bizon','Brass','Mil-Spec','The Dust 2 Collection'),
 (147,'MAC-10','Palm','Industrial','The Dust 2 Collection'),
 (148,'Tec-9','VariCamo','Industrial','The Dust 2 Collection'),
 (149,'Nova','Predator','Consumer','The Dust 2 Collection'),
 (150,'M4A1-S','VariCamo','Mil-Spec','The Dust 2 Collection'),
 (151,'XM1014','CaliCamo','Industrial','The Italy Collection'),
 (152,'Tec-9','Groundwater','Consumer','The Italy Collection'),
 (153,'Sawed-Off','Full Stop','Mil-Spec','The Italy Collection'),
 (154,'AUG','Contractor','Consumer','The Italy Collection'),
 (155,'M4A1-S','Boreal Forest','Industrial','The Italy Collection'),
 (156,'FAMAS','Colony','Consumer','The Italy Collection'),
 (157,'UMP-45','Gunsmoke','Industrial','The Italy Collection'),
 (158,'AWP','Pit Viper','Restricted','The Italy Collection'),
 (159,'Nova','Sand Dune','Consumer','The Italy Collection'),
 (160,'Glock-18','Candy Apple','Mil-Spec','The Italy Collection'),
 (161,'P2000','Granite Marbleized','Industrial','The Italy Collection'),
 (162,'Dual Berettas','Stained','Industrial','The Italy Collection'),
 (163,'MP7','Anodized Navy','Mil-Spec','The Italy Collection'),
 (164,'PP-Bizon','Sand Dashed','Consumer','The Italy Collection'),
 (165,'Nova','Candy Apple','Industrial','The Italy Collection'),
 (166,'P250','Boreal Forest','Consumer','The Lake Collection'),
 (167,'USP-S','Night Ops','Mil-Spec','The Lake Collection'),
 (168,'Desert Eagle','Mudder','Industrial','The Lake Collection'),
 (169,'XM1014','Blue Spruce','Consumer','The Lake Collection'),
 (170,'AUG','Storm','Consumer','The Lake Collection'),
 (171,'AWP','Safari Mesh','Industrial','The Lake Collection'),
 (172,'Dual Berettas','Cobalt Quartz','Restricted','The Lake Collection'),
 (173,'Galil AR','Sage Spray','Consumer','The Lake Collection'),
 (174,'PP-Bizon','Night Ops','Industrial','The Lake Collection'),
 (175,'P90','Teardown','Mil-Spec','The Lake Collection'),
 (176,'SG 553','Waves Perforated','Consumer','The Lake Collection'),
 (177,'G3SG1','Jungle Dashed','Consumer','The Lake Collection'),
 (178,'FAMAS','Cyanospatter','Industrial','The Lake Collection'),
 (179,'XM1014','Blue Steel','Industrial','The Lake Collection'),
 (180,'SG 553','Anodized Navy','Mil-Spec','The Lake Collection'),
 (181,'P250','Bone Mask','Consumer','The Mirage Collection'),
 (182,'Negev','CaliCamo','Industrial','The Mirage Collection'),
 (183,'Five-SeveN','Contractor','Consumer','The Mirage Collection'),
 (184,'AUG','Colony','Consumer','The Mirage Collection'),
 (185,'MAG-7','Bulldozer','Restricted','The Mirage Collection'),
 (186,'MAC-10','Amber Fade','Mil-Spec','The Mirage Collection'),
 (187,'G3SG1','Safari Mesh','Consumer','The Mirage Collection'),
 (188,'SSG 08','Tropical Storm','Industrial','The Mirage Collection'),
 (189,'P90','Scorched','Consumer','The Mirage Collection'),
 (190,'SG 553','Gator Mesh','Industrial','The Mirage Collection'),
 (191,'Galil AR','Hunting Blind','Consumer','The Mirage Collection'),
 (192,'Glock-18','Groundwater','Industrial','The Mirage Collection'),
 (193,'UMP-45','Blaze','Mil-Spec','The Mirage Collection'),
 (194,'MP7','Orange Peel','Industrial','The Mirage Collection'),
 (195,'MP9','Hot Rod','Mil-Spec','The Mirage Collection'),
 (196,'Dual Berettas','Contractor','Consumer','The Safehouse Collection'),
 (197,'SCAR-20','Contractor','Consumer','The Safehouse Collection'),
 (198,'G3SG1','VariCamo','Industrial','The Safehouse Collection'),
 (199,'SSG 08','Blue Spruce','Consumer','The Safehouse Collection'),
 (200,'SSG 08','Acid Fade','Mil-Spec','The Safehouse Collection'),
 (201,'M249','Gator Mesh','Industrial','The Safehouse Collection'),
 (202,'Galil AR','VariCamo','Industrial','The Safehouse Collection'),
 (203,'M4A1-S','Nitro','Restricted','The Safehouse Collection'),
 (204,'Tec-9','Army Mesh','Consumer','The Safehouse Collection'),
 (205,'Five-SeveN','Silver Quartz','Mil-Spec','The Safehouse Collection'),
 (206,'MP7','Army Recon','Consumer','The Safehouse Collection'),
 (207,'USP-S','Forest Leaves','Industrial','The Safehouse Collection'),
 (208,'AUG','Condemned','Industrial','The Safehouse Collection'),
 (209,'FAMAS','Teardown','Mil-Spec','The Safehouse Collection'),
 (210,'MP9','Orange Peel','Industrial','The Safehouse Collection'),
 (211,'UMP-45','Urban DDPAT','Consumer','The Train Collection'),
 (212,'P250','Metallic DDPAT','Industrial','The Train Collection'),
 (213,'Dual Berettas','Colony','Consumer','The Train Collection'),
 (214,'G3SG1','Polar Camo','Consumer','The Train Collection'),
 (215,'Desert Eagle','Urban Rubble','Mil-Spec','The Train Collection'),
 (216,'Tec-9','Red Quartz','Restricted','The Train Collection'),
 (217,'Five-SeveN','Forest Night','Consumer','The Train Collection'),
 (218,'MAG-7','Metallic DDPAT','Industrial','The Train Collection'),
 (219,'SCAR-20','Carbon Fiber','Industrial','The Train Collection'),
 (220,'Sawed-Off','Amber Fade','Mil-Spec','The Train Collection'),
 (221,'Nova','Polar Mesh','Consumer','The Train Collection'),
 (222,'P90','Ash Wood','Industrial','The Train Collection'),
 (223,'PP-Bizon','Urban Dashed','Consumer','The Train Collection'),
 (224,'MAC-10','Candy Apple','Industrial','The Train Collection'),
 (225,'M4A4','Urban DDPAT','Industrial','The Train Collection'),
 (226,'Galil AR','Sandstorm','Mil-Spec','The Winter Offensive Collection'),
 (227,'Five-SeveN','Kami','Mil-Spec','The Winter Offensive Collection'),
 (228,'M249','Magma','Mil-Spec','The Winter Offensive Collection'),
 (229,'PP-Bizon','Cobalt Halftone','Mil-Spec','The Winter Offensive Collection'),
 (230,'FAMAS','Pulse','Restricted','The Winter Offensive Collection'),
 (231,'Dual Berettas','Marina','Restricted','The Winter Offensive Collection'),
 (232,'MP9','Rose Iron','Restricted','The Winter Offensive Collection'),
 (233,'Nova','Rising Skull','Restricted','The Winter Offensive Collection'),
 (234,'M4A1-S','Guardian','Classified','The Winter Offensive Collection'),
 (235,'P250','Mehndi','Classified','The Winter Offensive Collection'),
 (236,'AWP','Redline','Classified','The Winter Offensive Collection'),
 (237,'M4A4','Asiimov','Covert','The Winter Offensive Collection'),
 (238,'Galil AR','Blue Titanium','Mil-Spec','The eSports 2013 Winter Collection'),
 (239,'AK-47','Blue Laminate','Restricted','The eSports 2013 Winter Collection'),
 (240,'Desert Eagle','Cobalt Disruption','Classified','The eSports 2013 Winter Collection'),
 (241,'PP-Bizon','Water Sigil','Mil-Spec','The eSports 2013 Winter Collection'),
 (242,'Nova','Ghost Camo','Mil-Spec','The eSports 2013 Winter Collection'),
 (243,'AWP','Electric Hive','Classified','The eSports 2013 Winter Collection'),
 (244,'M4A4','X-Ray','Covert','The eSports 2013 Winter Collection'),
 (245,'G3SG1','Azure Zebra','Mil-Spec','The eSports 2013 Winter Collection'),
 (246,'P250','Steel Disruption','Mil-Spec','The eSports 2013 Winter Collection'),
 (247,'P90','Blind Spot','Restricted','The eSports 2013 Winter Collection'),
 (248,'FAMAS','Afterimage','Classified','The eSports 2013 Winter Collection'),
 (249,'Five-SeveN','Nightshade','Mil-Spec','The eSports 2013 Winter Collection'),
 (250,'Sawed-Off','The Kraken','Covert','The Winter Offensive Collection'),
 (251,'CZ75-Auto','Crimson Web','Mil-Spec','The Arms Deal 3 Collection'),
 (252,'P2000','Red FragCam','Mil-Spec','The Arms Deal 3 Collection'),
 (253,'Dual Berettas','Panther','Mil-Spec','The Arms Deal 3 Collection'),
 (254,'USP-S','Stainless','Mil-Spec','The Arms Deal 3 Collection'),
 (255,'Glock-18','Blue Fissure','Mil-Spec','The Arms Deal 3 Collection'),
 (256,'CZ75-Auto','Tread Plate','Restricted','The Arms Deal 3 Collection'),
 (257,'Tec-9','Titanium Bit','Restricted','The Arms Deal 3 Collection'),
 (258,'Desert Eagle','Heirloom','Restricted','The Arms Deal 3 Collection'),
 (259,'Five-SeveN','Copper Galaxy','Restricted','The Arms Deal 3 Collection'),
 (260,'CZ75-Auto','The Fuschia Is Now','Classified','The Arms Deal 3 Collection'),
 (261,'P250','Undertow','Classified','The Arms Deal 3 Collection'),
 (262,'CZ75-Auto','Victoria','Covert','The Arms Deal 3 Collection'),
 (263,'UMP-45','Corporal','Mil-Spec','The Phoenix Collection'),
 (264,'Negev','Terrain','Mil-Spec','The Phoenix Collection'),
 (265,'Tec-9','Sandstorm','Mil-Spec','The Phoenix Collection'),
 (266,'MAG-7','Heaven Guard','Mil-Spec','The Phoenix Collection'),
 (267,'MAC-10','Heat','Restricted','The Phoenix Collection'),
 (268,'SG 553','Pulse','Restricted','The Phoenix Collection'),
 (269,'FAMAS','Sergeant','Restricted','The Phoenix Collection'),
 (270,'USP-S','Guardian','Restricted','The Phoenix Collection'),
 (271,'AK-47','Redline','Classified','The Phoenix Collection'),
 (272,'P90','Trigon','Classified','The Phoenix Collection'),
 (273,'Nova','Antique','Classified','The Phoenix Collection'),
 (274,'AWP','Asiimov','Covert','The Phoenix Collection'),
 (275,'AUG','Chameleon','Covert','The Phoenix Collection'),
 (276,'Gut Knife','★ (Vanilla)','Covert','CS:GO Weapon Case'),
 (277,'Gut Knife','Blue Steel','Covert','CS:GO Weapon Case'),
 (278,'Gut Knife','Boreal Forest','Covert','CS:GO Weapon Case'),
 (279,'Gut Knife','Case Hardened','Covert','CS:GO Weapon Case'),
 (280,'Gut Knife','Crimson Web','Covert','CS:GO Weapon Case'),
 (281,'Gut Knife','Fade','Covert','CS:GO Weapon Case'),
 (282,'Gut Knife','Forest DDPAT','Covert','CS:GO Weapon Case'),
 (283,'Gut Knife','Night','Covert','CS:GO Weapon Case'),
 (284,'Gut Knife','Safari Mesh','Covert','CS:GO Weapon Case'),
 (285,'Gut Knife','Scorched','Covert','CS:GO Weapon Case'),
 (286,'Gut Knife','Slaughter','Covert','CS:GO Weapon Case'),
 (287,'Gut Knife','Stained','Covert','CS:GO Weapon Case'),
 (288,'Gut Knife','Urban Masked','Covert','CS:GO Weapon Case'),
 (289,'Flip Knife','★ (Vanilla)','Covert','CS:GO Weapon Case'),
 (290,'Flip Knife','Blue Steel','Covert','CS:GO Weapon Case'),
 (291,'Flip Knife','Boreal Forest','Covert','CS:GO Weapon Case'),
 (292,'Flip Knife','Case Hardened','Covert','CS:GO Weapon Case'),
 (293,'Flip Knife','Crimson Web','Covert','CS:GO Weapon Case'),
 (294,'Flip Knife','Fade','Covert','CS:GO Weapon Case'),
 (295,'Flip Knife','Forest DDPAT','Covert','CS:GO Weapon Case'),
 (296,'Flip Knife','Night','Covert','CS:GO Weapon Case'),
 (297,'Flip Knife','Safari Mesh','Covert','CS:GO Weapon Case'),
 (298,'Flip Knife','Scorched','Covert','CS:GO Weapon Case'),
 (299,'Flip Knife','Slaughter','Covert','CS:GO Weapon Case'),
 (300,'Flip Knife','Stained','Covert','CS:GO Weapon Case'),
 (301,'Flip Knife','Urban Masked','Covert','CS:GO Weapon Case'),
 (302,'Bayonet','★ (Vanilla)','Covert','CS:GO Weapon Case'),
 (303,'Bayonet','Blue Steel','Covert','CS:GO Weapon Case'),
 (304,'Bayonet','Boreal Forest','Covert','CS:GO Weapon Case'),
 (305,'Bayonet','Case Hardened','Covert','CS:GO Weapon Case'),
 (306,'Bayonet','Crimson Web','Covert','CS:GO Weapon Case'),
 (307,'Bayonet','Fade','Covert','CS:GO Weapon Case'),
 (308,'Bayonet','Forest DDPAT','Covert','CS:GO Weapon Case'),
 (309,'Bayonet','Night','Covert','CS:GO Weapon Case'),
 (310,'Bayonet','Safari Mesh','Covert','CS:GO Weapon Case'),
 (311,'Bayonet','Scorched','Covert','CS:GO Weapon Case'),
 (312,'Bayonet','Slaughter','Covert','CS:GO Weapon Case'),
 (313,'Bayonet','Stained','Covert','CS:GO Weapon Case'),
 (314,'Bayonet','Urban Masked','Covert','CS:GO Weapon Case'),
 (315,'M9 Bayonet','★ (Vanilla)','Covert','CS:GO Weapon Case'),
 (316,'M9 Bayonet','Blue Steel','Covert','CS:GO Weapon Case'),
 (317,'M9 Bayonet','Boreal Forest','Covert','CS:GO Weapon Case'),
 (318,'M9 Bayonet','Case Hardened','Covert','CS:GO Weapon Case'),
 (319,'M9 Bayonet','Crimson Web','Covert','CS:GO Weapon Case'),
 (320,'M9 Bayonet','Fade','Covert','CS:GO Weapon Case'),
 (321,'M9 Bayonet','Forest DDPAT','Covert','CS:GO Weapon Case'),
 (322,'M9 Bayonet','Night','Covert','CS:GO Weapon Case'),
 (323,'M9 Bayonet','Safari Mesh','Covert','CS:GO Weapon Case'),
 (324,'M9 Bayonet','Scorched','Covert','CS:GO Weapon Case'),
 (325,'M9 Bayonet','Slaughter','Covert','CS:GO Weapon Case'),
 (326,'M9 Bayonet','Stained','Covert','CS:GO Weapon Case'),
 (327,'M9 Bayonet','Urban Masked','Covert','CS:GO Weapon Case'),
 (328,'Karambit','★ (Vanilla)','Covert','CS:GO Weapon Case'),
 (329,'Karambit','Blue Steel','Covert','CS:GO Weapon Case'),
 (330,'Karambit','Boreal Forest','Covert','CS:GO Weapon Case'),
 (331,'Karambit','Case Hardened','Covert','CS:GO Weapon Case'),
 (332,'Karambit','Crimson Web','Covert','CS:GO Weapon Case'),
 (333,'Karambit','Fade','Covert','CS:GO Weapon Case'),
 (334,'Karambit','Forest DDPAT','Covert','CS:GO Weapon Case'),
 (335,'Karambit','Night','Covert','CS:GO Weapon Case'),
 (336,'Karambit','Safari Mesh','Covert','CS:GO Weapon Case'),
 (337,'Karambit','Scorched','Covert','CS:GO Weapon Case'),
 (338,'Karambit','Slaughter','Covert','CS:GO Weapon Case'),
 (339,'Karambit','Stained','Covert','CS:GO Weapon Case'),
 (340,'Karambit','Urban Masked','Covert','CS:GO Weapon Case'),
 (341,'Tec-9','Isaac','Mil-Spec','The Huntsman Collection'),
 (342,'SSG 08','Slashed','Mil-Spec','The Huntsman Collection'),
 (343,'Dual Berettas','Retribution','Mil-Spec','The Huntsman Collection'),
 (344,'Galil AR','Kami','Mil-Spec','The Huntsman Collection'),
 (345,'P90','Desert Warfare','Mil-Spec','The Huntsman Collection'),
 (346,'CZ75-Auto','Poison Dart','Mil-Spec','The Huntsman Collection'),
 (347,'AUG','Torque','Restricted','The Huntsman Collection'),
 (348,'PP-Bizon','Antique','Restricted','The Huntsman Collection'),
 (349,'MAC-10','Curse','Restricted','The Huntsman Collection'),
 (350,'XM1014','Heaven Guard','Restricted','The Huntsman Collection'),
 (351,'M4A1-S','Atomic Alloy','Classified','The Huntsman Collection'),
 (352,'SCAR-20','Cyrex','Classified','The Huntsman Collection'),
 (353,'USP-S','Orion','Classified','The Huntsman Collection'),
 (354,'AK-47','Vulcan','Covert','The Huntsman Collection'),
 (355,'M4A4','Howl','Contraband','The Office Collection
'),
 (356,'P250','Franklin','Classified','The Bank Collection'),
 (357,'AK-47','Emerald Pinstripe','Restricted','The Bank Collection'),
 (358,'CZ75-Auto','Tuxedo','Mil-Spec','The Bank Collection'),
 (359,'Desert Eagle','Meteorite','Mil-Spec','The Bank Collection'),
 (360,'G3SG1','Green Apple','Industrial','The Bank Collection'),
 (361,'Galil AR','Tuxedo','Mil-Spec','The Bank Collection'),
 (362,'Glock-18','Death Rattle','Industrial','The Bank Collection'),
 (363,'MAC-10','Silver','Industrial','The Bank Collection'),
 (364,'MP7','Forest DDPAT','Consumer','The Bank Collection'),
 (365,'Negev','Army Sheen','Consumer','The Bank Collection'),
 (366,'Nova','Caged Steel','Industrial','The Bank Collection'),
 (367,'Sawed-Off','Forest DDPAT','Consumer','The Bank Collection'),
 (368,'SG 553','Army Sheen','Consumer','The Bank Collection'),
 (369,'Tec-9','Urban DDPAT','Consumer','The Bank Collection'),
 (370,'UMP-45','Carbon Fiber','Industrial','The Bank Collection'),
 (372,'Huntsman Knife','★ (Vanilla)','Covert','Huntsman Weapon Case'),
 (373,'Huntsman Knife','Blue Steel','Covert','Huntsman Weapon Case'),
 (374,'Huntsman Knife','Boreal Forest','Covert','Huntsman Weapon Case'),
 (375,'Huntsman Knife','Case Hardened','Covert','Huntsman Weapon Case'),
 (376,'Huntsman Knife','Crimson Web','Covert','Huntsman Weapon Case'),
 (377,'Huntsman Knife','Fade','Covert','Huntsman Weapon Case'),
 (378,'Huntsman Knife','Forest DDPAT','Covert','Huntsman Weapon Case'),
 (379,'Huntsman Knife','Night','Covert','Huntsman Weapon Case'),
 (380,'Huntsman Knife','Safari Mesh','Covert','Huntsman Weapon Case'),
 (381,'Huntsman Knife','Scorched','Covert','Huntsman Weapon Case'),
 (382,'Huntsman Knife','Slaughter','Covert','Huntsman Weapon Case'),
 (383,'Huntsman Knife','Stained','Covert','Huntsman Weapon Case'),
 (384,'Huntsman Knife','Urban Masked','Covert','Huntsman Weapon Case'),
 (385,'CZ75-Auto','Twist','Mil-Spec','The Huntsman Collection'),
 (386,'P90','Module','Mil-Spec','The Huntsman Collection'),
 (387,'P2000','Pulse','Mil-Spec','The Huntsman Collection'),
 (388,'MAC-10','Tatter','Restricted','The Huntsman Collection'),
 (390,'USP-S','Caiman','Classified','The Huntsman Collection'),
 (391,'M4A4','Desert-Strike','Covert','The Huntsman Collection'),
 (393,'M4A1-S','Cyrex','Covert','The Breakout Collection'),
 (394,'MP7','Urban Hazard','Mil-Spec','The Breakout Collection'),
 (395,'Negev','Desert-Strike','Mil-Spec','The Breakout Collection'),
 (396,'Nova','Koi','Restricted','The Breakout Collection'),
 (397,'P250','Supernova','Restricted','The Breakout Collection'),
 (398,'SSG 08','Abyss','Mil-Spec','The Breakout Collection'),
 (399,'UMP-45','Labyrinth','Mil-Spec','The Breakout Collection'),
 (400,'PP-Bizon','Osiris','Restricted','The Breakout Collection'),
 (401,'CZ75-Auto','Tigris','Restricted','The Breakout Collection'),
 (402,'Desert Eagle','Conspiracy','Classified','The Breakout Collection'),
 (403,'Five-SeveN','Fowl Play','Classified','The Breakout Collection'),
 (404,'Glock-18','Water Elemental','Classified','The Breakout Collection'),
 (405,'P2000','Ivory','Mil-Spec','The Breakout Collection'),
 (406,'P90','Asiimov','Covert','The Breakout Collection'),
 (407,'P90','Leather','Industrial','The Baggage Collection'),
 (408,'MAC-10','Commuter','Industrial','The Baggage Collection'),
 (409,'Sawed-Off','First Class','Mil-Spec','The Baggage Collection'),
 (410,'P2000','Coach Class','Industrial','The Baggage Collection'),
 (411,'USP-S','Business Class','Mil-Spec','The Baggage Collection'),
 (412,'G3SG1','Contractor','Consumer','The Baggage Collection'),
 (413,'MP7','Olive Plaid','Consumer','The Baggage Collection'),
 (414,'CZ75-Auto','Green Plaid','Consumer','The Baggage Collection'),
 (415,'MP9','Green Plaid','Consumer','The Baggage Collection'),
 (416,'SSG 08','Sand Dune','Consumer','The Baggage Collection'),
 (417,'SG 553','Traveler','Industrial','The Baggage Collection'),
 (418,'XM1014','Red Leather','Mil-Spec','The Baggage Collection'),
 (419,'Desert Eagle','Pilot','Restricted','The Baggage Collection'),
 (420,'AK-47','Jet Set','Classified','The Baggage Collection'),
 (421,'AK-47','First Class','Restricted','The Baggage Collection'),
 (422,'AWP','Dragon Lore','Covert','The Cobblestone Collection'),
 (423,'P90','Storm','Consumer','The Cobblestone Collection'),
 (424,'UMP-45','Indigo','Consumer','The Cobblestone Collection'),
 (425,'MAC-10','Indigo','Consumer','The Cobblestone Collection'),
 (426,'SCAR-20','Storm','Consumer','The Cobblestone Collection'),
 (427,'USP-S','Royal Blue','Industrial','The Cobblestone Collection'),
 (428,'Dual Berettas','Briar','Consumer','The Cobblestone Collection'),
 (429,'Nova','Green Apple','Industrial','The Cobblestone Collection'),
 (430,'MAG-7','Silver','Industrial','The Cobblestone Collection'),
 (431,'MP9','Dark Age','Mil-Spec','The Cobblestone Collection'),
 (432,'Desert Eagle','Hand Cannon','Restricted','The Cobblestone Collection'),
 (433,'P2000','Chainmail','Mil-Spec','The Cobblestone Collection'),
 (434,'Sawed-Off','Rust Coat','Industrial','The Cobblestone Collection'),
 (435,'M4A1-S','Knight','Classified','The Cobblestone Collection'),
 (436,'CZ75-Auto','Chalice','Restricted','The Cobblestone Collection'),
 (437,'M4A1-S','Master Piece','Classified','The Overpass Collection'),
 (438,'Desert Eagle','Urban DDPAT','Industrial','The Overpass Collection'),
 (439,'MP7','Gunsmoke','Industrial','The Overpass Collection'),
 (440,'Glock-18','Night','Industrial','The Overpass Collection'),
 (441,'P2000','Grassland','Industrial','The Overpass Collection'),
 (442,'CZ75-Auto','Nitro','Mil-Spec','The Overpass Collection'),
 (443,'Sawed-Off','Sage Spray','Consumer','The Overpass Collection'),
 (444,'UMP-45','Scorched','Consumer','The Overpass Collection'),
 (445,'M249','Contrast Spray','Consumer','The Overpass Collection'),
 (446,'MAG-7','Storm','Consumer','The Overpass Collection'),
 (447,'MP9','Storm','Consumer','The Overpass Collection'),
 (448,'XM1014','VariCamo Blue','Mil-Spec','The Overpass Collection'),
 (449,'AWP','Pink DDPAT','Restricted','The Overpass Collection'),
 (450,'USP-S','Road Rash','Restricted','The Overpass Collection'),
 (451,'SSG 08','Detour','Mil-Spec','The Overpass Collection'),
 (452,'Butterfly Knife','★ (Vanilla)','Covert','Operation Breakout Weapon Case'),
 (453,'Butterfly Knife','Blue Steel','Covert','Operation Breakout Weapon Case'),
 (454,'Butterfly Knife','Boreal Forest','Covert','Operation Breakout Weapon Case'),
 (455,'Butterfly Knife','Case Hardened','Covert','Operation Breakout Weapon Case'),
 (456,'Butterfly Knife','Crimson Web','Covert','Operation Breakout Weapon Case'),
 (457,'Butterfly Knife','Fade','Covert','Operation Breakout Weapon Case'),
 (458,'Butterfly Knife','Forest DDPAT','Covert','Operation Breakout Weapon Case'),
 (459,'Butterfly Knife','Night','Covert','Operation Breakout Weapon Case'),
 (460,'Butterfly Knife','Safari Mesh','Covert','Operation Breakout Weapon Case'),
 (461,'Butterfly Knife','Scorched','Covert','Operation Breakout Weapon Case'),
 (462,'Butterfly Knife','Slaughter','Covert','Operation Breakout Weapon Case'),
 (463,'Butterfly Knife','Stained','Covert','Operation Breakout Weapon Case'),
 (464,'Butterfly Knife','Urban Masked','Covert','Operation Breakout Weapon Case'),
 (465,'M4A4','Bullet Rain','Covert','The eSports 2014 Summer Collection'),
 (466,'P2000','Corticera','Classified','The eSports 2014 Summer Collection'),
 (467,'AWP','Corticera','Classified','The eSports 2014 Summer Collection'),
 (468,'AK-47','Jaguar','Covert','The eSports 2014 Summer Collection'),
 (469,'Nova','Bloomstick','Classified','The eSports 2014 Summer Collection'),
 (470,'AUG','Bengal Tiger','Classified','The eSports 2014 Summer Collection'),
 (471,'Desert Eagle','Crimson Web','Restricted','The eSports 2014 Summer Collection'),
 (472,'Glock-18','Steel Disruption','Restricted','The eSports 2014 Summer Collection'),
 (473,'MP7','Ocean Foam','Restricted','The eSports 2014 Summer Collection'),
 (474,'PP-Bizon','Blue Streak','Restricted','The eSports 2014 Summer Collection'),
 (475,'XM1014','Red Python','Mil-Spec','The eSports 2014 Summer Collection'),
 (476,'Negev','Bratatat','Mil-Spec','The eSports 2014 Summer Collection'),
 (477,'CZ75-Auto','Hexane','Mil-Spec','The eSports 2014 Summer Collection'),
 (478,'USP-S','Blood Tiger','Mil-Spec','The eSports 2014 Summer Collection'),
 (479,'MAC-10','Ultraviolet','Mil-Spec','The eSports 2014 Summer Collection'),
 (480,'SSG 08','Dark Water','Mil-Spec','The eSports 2014 Summer Collection'),
 (481,'P90','Virus','Restricted','The eSports 2014 Summer Collection'),
 (482,'Galil AR','Cerberus','Restricted','The Cache Collection'),
 (483,'Tec-9','Toxic','Mil-Spec','The Cache Collection'),
 (484,'Glock-18','Reactor','Mil-Spec','The Cache Collection'),
 (485,'XM1014','Bone Machine','Mil-Spec','The Cache Collection'),
 (486,'MAC-10','Nuclear Garden','Mil-Spec','The Cache Collection'),
 (487,'AUG','Radiation Hazard','Industrial','The Cache Collection'),
 (488,'MP9','Setting Sun','Mil-Spec','The Cache Collection'),
 (489,'PP-Bizon','Chemical Green','Industrial','The Cache Collection'),
 (490,'Negev','Nuclear Waste','Industrial','The Cache Collection'),
 (491,'FAMAS','Styx','Restricted','The Cache Collection'),
 (492,'P250','Contamination','Industrial','The Cache Collection'),
 (493,'Five-SeveN','Hot Shot','Industrial','The Cache Collection'),
 (494,'SG 553','Fallout Warning','Industrial','The Cache Collection'),
 (495,'AK-47','Wasteland Rebel','Covert','The Vanguard Collection'),
 (496,'Five-SeveN','Urban Hazard','Mil-Spec','The Vanguard Collection'),
 (497,'G3SG1','Murky','Mil-Spec','The Vanguard Collection'),
 (498,'Glock-18','Grinder','Restricted','The Vanguard Collection'),
 (499,'M4A1-S','Basilisk','Restricted','The Vanguard Collection'),
 (500,'M4A4','Griffin','Restricted','The Vanguard Collection'),
 (501,'MAG-7','Firestarter','Mil-Spec','The Vanguard Collection'),
 (502,'MP9','Dart','Mil-Spec','The Vanguard Collection'),
 (503,'P250','Cartel','Classified','The Vanguard Collection'),
 (504,'P2000','Fire Elemental','Covert','The Vanguard Collection'),
 (505,'Sawed-Off','Highwayman','Restricted','The Vanguard Collection'),
 (506,'SCAR-20','Cardiac','Classified','The Vanguard Collection'),
 (507,'UMP-45','Delusion','Mil-Spec','The Vanguard Collection'),
 (508,'XM1014','Tranquility','Classified','The Vanguard Collection'),
 (509,'AK-47','Cartel','Classified','The Chroma Collection'),
 (510,'AWP','Man-o''-war','Covert','The Chroma Collection'),
 (511,'Desert Eagle','Naga','Restricted','The Chroma Collection'),
 (512,'Galil AR','Chatterbox','Covert','The Chroma Collection'),
 (513,'Glock-18','Catacombs','Mil-Spec','The Chroma Collection'),
 (514,'M249','System Lock','Mil-Spec','The Chroma Collection'),
 (515,'XM1014','Quicksilver','Mil-Spec','The Chroma Collection'),
 (516,'MAC-10','Malachite','Restricted','The Chroma Collection'),
 (517,'MP9','Deadly Poison','Mil-Spec','The Chroma Collection'),
 (518,'P250','Muertos','Classified','The Chroma Collection'),
 (519,'M4A4','龍王 (Dragon King)','Classified','The Chroma Collection'),
 (520,'Sawed-Off','Serenity','Restricted','The Chroma Collection'),
 (521,'SCAR-20','Grotto','Mil-Spec','The Chroma Collection'),
 (522,'Dual Berettas','Urban Shock','Restricted','The Chroma Collection'),
 (523,'Gut Knife','Damascus Steel','Covert','Chroma Case'),
 (524,'Gut Knife','Doppler','Covert','Chroma Case'),
 (525,'Gut Knife','Marble Fade','Covert','Chroma Case'),
 (526,'Gut Knife','Tiger Tooth','Covert','Chroma Case'),
 (527,'Gut Knife','Rust Coat','Covert','Chroma Case'),
 (528,'Gut Knife','Ultraviolet','Covert','Chroma Case'),
 (529,'Flip Knife','Damascus Steel','Covert','Chroma Case'),
 (530,'Flip Knife','Doppler','Covert','Chroma Case'),
 (531,'Flip Knife','Marble Fade','Covert','Chroma Case'),
 (532,'Flip Knife','Tiger Tooth','Covert','Chroma Case'),
 (533,'Flip Knife','Rust Coat','Covert','Chroma Case'),
 (534,'Flip Knife','Ultraviolet','Covert','Chroma Case'),
 (535,'Bayonet','Damascus Steel','Covert','Chroma Case'),
 (536,'Bayonet','Doppler','Covert','Chroma Case'),
 (537,'Bayonet','Marble Fade','Covert','Chroma Case'),
 (538,'Bayonet','Tiger Tooth','Covert','Chroma Case'),
 (539,'Bayonet','Rust Coat','Covert','Chroma Case'),
 (540,'Bayonet','Ultraviolet','Covert','Chroma Case'),
 (541,'M9 Bayonet','Damascus Steel','Covert','Chroma Case'),
 (542,'M9 Bayonet','Doppler','Covert','Chroma Case'),
 (543,'M9 Bayonet','Marble Fade','Covert','Chroma Case'),
 (544,'M9 Bayonet','Tiger Tooth','Covert','Chroma Case'),
 (545,'M9 Bayonet','Rust Coat','Covert','Chroma Case'),
 (546,'M9 Bayonet','Ultraviolet','Covert','Chroma Case'),
 (547,'Karambit','Damascus Steel','Covert','Chroma Case'),
 (548,'Karambit','Doppler','Covert','Chroma Case'),
 (549,'Karambit','Marble Fade','Covert','Chroma Case'),
 (550,'Karambit','Tiger Tooth','Covert','Chroma Case'),
 (551,'Karambit','Rust Coat','Covert','Chroma Case'),
 (552,'Karambit','Ultraviolet','Covert','Chroma Case'),
 (553,'MAC-10','Neon Rider','Covert','The Chroma 2 Collection'),
 (554,'M4A1-S','Hyper Beast','Covert','The Chroma 2 Collection'),
 (555,'FAMAS','Djinn','Classified','The Chroma 2 Collection'),
 (556,'Galil AR','Eco','Classified','The Chroma 2 Collection'),
 (557,'Five-SeveN','Monkey Business','Classified','The Chroma 2 Collection'),
 (558,'UMP-45','Grand Prix','Restricted','The Chroma 2 Collection'),
 (559,'CZ75-Auto','Pole Position','Restricted','The Chroma 2 Collection'),
 (560,'MAG-7','Heat','Restricted','The Chroma 2 Collection'),
 (561,'AWP','Worm God','Restricted','The Chroma 2 Collection'),
 (562,'Sawed-Off','Origami','Mil-Spec','The Chroma 2 Collection'),
 (563,'Negev','Man-o''-war','Mil-Spec','The Chroma 2 Collection'),
 (564,'P250','Valence','Mil-Spec','The Chroma 2 Collection'),
 (565,'Desert Eagle','Bronze Deco','Mil-Spec','The Chroma 2 Collection'),
 (566,'MP7','Armor Core','Mil-Spec','The Chroma 2 Collection'),
 (567,'AK-47','Elite Build','Mil-Spec','The Chroma 2 Collection'),
 (568,'AWP','Hyper Beast','Covert','The Falchion Collection'),
 (569,'AK-47','Aquamarine Revenge','Covert','The Falchion Collection'),
 (570,'SG 553','Cyrex','Classified','The Falchion Collection'),
 (571,'MP7','Nemesis','Classified','The Falchion Collection'),
 (572,'CZ75-Auto','Yellow Jacket','Classified','The Falchion Collection'),
 (573,'P2000','Handgun','Restricted','The Falchion Collection'),
 (574,'Negev','Loudmouth','Restricted','The Falchion Collection'),
 (575,'MP9','Ruby Poison Dart','Restricted','The Falchion Collection'),
 (576,'M4A4','Evil Daimyo','Restricted','The Falchion Collection'),
 (577,'FAMAS','Neural Net','Restricted','The Falchion Collection'),
 (578,'USP-S','Torque','Mil-Spec','The Falchion Collection'),
 (579,'UMP-45','Riot','Mil-Spec','The Falchion Collection'),
 (580,'P90','Elite Build','Mil-Spec','The Falchion Collection'),
 (581,'Nova','Ranger','Mil-Spec','The Falchion Collection'),
 (582,'Glock-18','Bunsen Burner','Mil-Spec','The Falchion Collection'),
 (583,'Galil AR','Rocket Pop','Mil-Spec','The Falchion Collection'),
 (584,'SCAR-20','Army Sheen','Consumer','The Chop Shop Collection'),
 (585,'CZ75-Auto','Army Sheen','Consumer','The Chop Shop Collection'),
 (586,'M249','Impact Drill','Consumer','The Chop Shop Collection'),
 (587,'MAG-7','Seabird','Consumer','The Chop Shop Collection'),
 (588,'Desert Eagle','Night','Industrial','The Chop Shop Collection'),
 (589,'Galil AR','Urban Rubble','Industrial','The Chop Shop Collection'),
 (590,'USP-S','Para Green','Industrial','The Chop Shop Collection'),
 (591,'MAC-10','Fade','Mil-Spec','The Chop Shop Collection'),
 (592,'P250','Whiteout','Mil-Spec','The Chop Shop Collection'),
 (593,'MP7','Full Stop','Mil-Spec','The Chop Shop Collection'),
 (594,'Five-SeveN','Nitro','Mil-Spec','The Chop Shop Collection'),
 (595,'CZ75-Auto','Emerald','Mil-Spec','The Chop Shop Collection'),
 (596,'SG 553','Bulldozer','Restricted','The Chop Shop Collection'),
 (597,'Dual Berettas','Duelist','Restricted','The Chop Shop Collection'),
 (598,'Glock-18','Twilight Galaxy','Classified','The Chop Shop Collection'),
 (599,'M4A1-S','Hot Rod','Classified','The Chop Shop Collection'),
 (600,'MP7','Asterion','Consumer','The Gods and Monsters Collection'),
 (601,'AUG','Daedalus','Consumer','The Gods and Monsters Collection'),
 (602,'Dual Berettas','Moon in Libra','Consumer','The Gods and Monsters Collection'),
 (603,'Nova','Moon in Libra','Consumer','The Gods and Monsters Collection'),
 (604,'Tec-9','Hades','Industrial','The Gods and Monsters Collection'),
 (605,'P2000','Pathfinder','Industrial','The Gods and Monsters Collection'),
 (606,'AWP','Sun in Leo','Industrial','The Gods and Monsters Collection'),
 (607,'M249','Shipping Forecast','Industrial','The Gods and Monsters Collection'),
 (608,'UMP-45','Minotaur''s Labyrinth','Mil-Spec','The Gods and Monsters Collection'),
 (609,'MP9','Pandora''s Box','Mil-Spec','The Gods and Monsters Collection'),
 (610,'G3SG1','Chronos','Restricted','The Gods and Monsters Collection'),
 (611,'M4A1-S','Icarus Fell','Restricted','The Gods and Monsters Collection'),
 (612,'M4A4','Poseidon','Classified','The Gods and Monsters Collection'),
 (613,'AWP','Medusa','Covert','The Gods and Monsters Collection'),
 (614,'PP-Bizon','Bamboo Print','Consumer','The Rising Sun Collection'),
 (615,'Sawed-Off','Bamboo Shadow','Consumer','The Rising Sun Collection'),
 (616,'Tec-9','Bamboo Forest','Consumer','The Rising Sun Collection'),
 (617,'G3SG1','Orange Kimono','Consumer','The Rising Sun Collection'),
 (618,'P250','Mint Kimono','Consumer','The Rising Sun Collection'),
 (619,'P250','Crimson Kimono','Industrial','The Rising Sun Collection'),
 (620,'Desert Eagle','Midnight Storm','Industrial','The Rising Sun Collection'),
 (621,'Galil AR','Aqua Terrace','Mil-Spec','The Rising Sun Collection'),
 (622,'MAG-7','Counter Terrace','Mil-Spec','The Rising Sun Collection'),
 (623,'Tec-9','Terrace','Mil-Spec','The Rising Sun Collection'),
 (624,'Five-SeveN','Neon Kimono','Restricted','The Rising Sun Collection'),
 (625,'Desert Eagle','Sunset Storm 壱','Restricted','The Rising Sun Collection'),
 (626,'Desert Eagle','Sunset Storm 弐','Restricted','The Rising Sun Collection'),
 (627,'M4A4','Daybreak','Restricted','The Rising Sun Collection'),
 (628,'AK-47','Hydroponic','Classified','The Rising Sun Collection'),
 (629,'AUG','Akihabara Accept','Covert','The Rising Sun Collection'),
 (630,'Falchion Knife','★ (Vanilla)','Covert','Falchion Case'),
 (631,'Falchion Knife','Blue Steel','Covert','Falchion Case'),
 (632,'Falchion Knife','Boreal Forest','Covert','Falchion Case'),
 (633,'Falchion Knife','Case Hardened','Covert','Falchion Case'),
 (634,'Falchion Knife','Crimson Web','Covert','Falchion Case'),
 (635,'Falchion Knife','Fade','Covert','Falchion Case'),
 (636,'Falchion Knife','Forest DDPAT','Covert','Falchion Case'),
 (637,'Falchion Knife','Night','Covert','Falchion Case'),
 (638,'Falchion Knife','Safari Mesh','Covert','Falchion Case'),
 (639,'Falchion Knife','Scorched','Covert','Falchion Case'),
 (640,'Falchion Knife','Slaughter','Covert','Falchion Case'),
 (641,'Falchion Knife','Stained','Covert','Falchion Case'),
 (642,'Falchion Knife','Urban Masked','Covert','Falchion Case'),
 (643,'Dual Berettas','Dualing Dragons','Mil-Spec','The Shadow Collection'),
 (644,'FAMAS','Survivor Z','Mil-Spec','The Shadow Collection'),
 (645,'Glock-18','Wraiths','Mil-Spec','The Shadow Collection'),
 (646,'MAC-10','Rangeen','Mil-Spec','The Shadow Collection'),
 (647,'MAG-7','Cobalt Core','Mil-Spec','The Shadow Collection'),
 (648,'SCAR-20','Green Marine','Mil-Spec','The Shadow Collection'),
 (649,'XM1014','Scumbria','Mil-Spec','The Shadow Collection'),
 (650,'Galil AR','Stone Cold','Restricted','The Shadow Collection'),
 (651,'M249','Nebula Crusader','Restricted','The Shadow Collection'),
 (652,'MP7','Special Delivery','Restricted','The Shadow Collection'),
 (653,'P250','Wingshot','Restricted','The Shadow Collection'),
 (654,'AK-47','Frontside Misty','Classified','The Shadow Collection'),
 (655,'G3SG1','Flux','Classified','The Shadow Collection'),
 (656,'SSG 08','Big Iron','Classified','The Shadow Collection'),
 (657,'M4A1-S','Golden Coil','Covert','The Shadow Collection'),
 (658,'USP-S','Kill Confirmed','Covert','The Shadow Collection'),
 (659,'Shadow Daggers','★ (Vanilla)','Covert','Shadow Case'),
 (660,'Shadow Daggers','Blue Steel','Covert','Shadow Case'),
 (661,'Shadow Daggers','Boreal Forest','Covert','Shadow Case'),
 (662,'Shadow Daggers','Case Hardened','Covert','Shadow Case'),
 (663,'Shadow Daggers','Crimson Web','Covert','Shadow Case'),
 (664,'Shadow Daggers','Fade','Covert','Shadow Case'),
 (665,'Shadow Daggers','Forest DDPAT','Covert','Shadow Case'),
 (666,'Shadow Daggers','Night','Covert','Shadow Case'),
 (667,'Shadow Daggers','Safari Mesh','Covert','Shadow Case'),
 (668,'Shadow Daggers','Scorched','Covert','Shadow Case'),
 (669,'Shadow Daggers','Slaughter','Covert','Shadow Case'),
 (670,'Shadow Daggers','Stained','Covert','Shadow Case'),
 (671,'Shadow Daggers','Urban Masked','Covert','Shadow Case'),
 (672,'R8 Revolver','Fade','Covert','The Revolver Case Collection'),
 (673,'M4A4','Royal Paladin','Covert','The Revolver Case Collection'),
 (674,'R8 Revolver','Crimson Web','Mil-Spec','The Revolver Case Collection'),
 (675,'AUG','Ricochet','Mil-Spec','The Revolver Case Collection'),
 (676,'Desert Eagle','Corinthian','Mil-Spec','The Revolver Case Collection'),
 (677,'P2000','Imperial','Mil-Spec','The Revolver Case Collection'),
 (678,'Sawed-Off','Yorick','Mil-Spec','The Revolver Case Collection'),
 (679,'SCAR-20','Outbreak','Mil-Spec','The Revolver Case Collection'),
 (680,'PP-Bizon','Fuel Rod','Restricted','The Revolver Case Collection'),
 (681,'Negev','Power Loader','Restricted','The Revolver Case Collection'),
 (682,'Five-SeveN','Retrobution','Restricted','The Revolver Case Collection'),
 (683,'SG 553','Tiger Moth','Restricted','The Revolver Case Collection'),
 (684,'Tec-9','Avalanche','Restricted','The Revolver Case Collection'),
 (685,'XM1014','Teclu Burner','Restricted','The Revolver Case Collection'),
 (686,'AK-47','Point Disarray','Classified','The Revolver Case Collection'),
 (687,'P90','Shapewood','Classified','The Revolver Case Collection'),
 (688,'G3SG1','The Executioner','Classified','The Revolver Case Collection'),
 (689,'R8 Revolver','Amber Fade','Classified','The Dust 2 Collection'),
 (690,'R8 Revolver','Bone Mask','Consumer','The Bank Collection'),
 (706,'PP-Bizon','Photic Zone','Mil-Spec','The Wildfire Collection'),
 (707,'Dual Berettas','Cartel','Mil-Spec','The Wildfire Collection'),
 (708,'MAC-10','Lapis Gator','Mil-Spec','The Wildfire Collection'),
 (709,'SSG 08','Necropos','Mil-Spec','The Wildfire Collection'),
 (710,'Tec-9','Jambiya','Mil-Spec','The Wildfire Collection'),
 (711,'USP-S','Lead Conduit','Mil-Spec','The Wildfire Collection'),
 (712,'FAMAS','Valence','Restricted','The Wildfire Collection'),
 (713,'Five-SeveN','Triumvirate','Restricted','The Wildfire Collection'),
 (714,'Glock-18','Royal Legion','Restricted','The Wildfire Collection'),
 (715,'MAG-7','Praetorian','Restricted','The Wildfire Collection'),
 (716,'MP7','Impire','Restricted','The Wildfire Collection'),
 (717,'AWP','Elite Build','Classified','The Wildfire Collection'),
 (718,'Desert Eagle','Kumicho Dragon','Classified','The Wildfire Collection'),
 (719,'Nova','Hyper Beast','Classified','The Wildfire Collection'),
 (720,'AK-47','Fuel Injector','Covert','The Wildfire Collection'),
 (721,'M4A4','The Battlestar','Covert','The Wildfire Collection'),
 (722,'Bowie Knife','★ (Vanilla)','Covert','Operation Wildfire Case'),
 (723,'Bowie Knife','Blue Steel','Covert','Operation Wildfire Case'),
 (724,'Bowie Knife','Boreal Forest','Covert','Operation Wildfire Case'),
 (725,'Bowie Knife','Case Hardened','Covert','Operation Wildfire Case'),
 (726,'Bowie Knife','Crimson Web','Covert','Operation Wildfire Case'),
 (727,'Bowie Knife','Fade','Covert','Operation Wildfire Case'),
 (728,'Bowie Knife','Forest DDPAT','Covert','Operation Wildfire Case'),
 (729,'Bowie Knife','Night','Covert','Operation Wildfire Case'),
 (730,'Bowie Knife','Safari Mesh','Covert','Operation Wildfire Case'),
 (731,'Bowie Knife','Scorched','Covert','Operation Wildfire Case'),
 (732,'Bowie Knife','Slaughter','Covert','Operation Wildfire Case'),
 (733,'Bowie Knife','Stained','Covert','Operation Wildfire Case'),
 (734,'Bowie Knife','Urban Masked','Covert','Operation Wildfire Case'),
 (735,'AUG','Fleet Flock','Classified','The Chroma 3 Collection'),
 (736,'PP-Bizon','Judgement of Anubis','Covert','The Chroma 3 Collection'),
 (737,'CZ75-Auto','Red Astor','Restricted','The Chroma 3 Collection'),
 (738,'Dual Berettas','Ventilators','Mil-Spec','The Chroma 3 Collection'),
 (739,'G3SG1','Orange Crash','Mil-Spec','The Chroma 3 Collection'),
 (740,'Galil AR','Firefight','Restricted','The Chroma 3 Collection'),
 (741,'M249','Spectre','Mil-Spec','The Chroma 3 Collection'),
 (742,'M4A1-S','Chantico''s Fire','Covert','The Chroma 3 Collection'),
 (743,'MP9','Bioleak','Mil-Spec','The Chroma 3 Collection'),
 (744,'P2000','Oceanic','Mil-Spec','The Chroma 3 Collection'),
 (745,'P250','Asiimov','Classified','The Chroma 3 Collection'),
 (746,'Sawed-Off','Fubar','Mil-Spec','The Chroma 3 Collection'),
 (747,'SG 553','Atlas','Mil-Spec','The Chroma 3 Collection'),
 (748,'SSG 08','Ghost Crusader','Restricted','The Chroma 3 Collection'),
 (749,'Tec-9','Re-Entry','Restricted','The Chroma 3 Collection'),
 (750,'UMP-45','Primal Saber','Classified','The Chroma 3 Collection'),
 (751,'XM1014','Black Tie','Restricted','The Chroma 3 Collection'),
 (752,'M4A1-S','Mecha Industries','Covert','The Gamma Collection'),
 (753,'Glock-18','Wasteland Rebel','Covert','The Gamma Collection'),
 (754,'SCAR-20','Bloodsport','Classified','The Gamma Collection'),
 (755,'P2000','Imperial Dragon','Classified','The Gamma Collection'),
 (756,'M4A4','Desolate Space','Classified','The Gamma Collection'),
 (757,'Sawed-Off','Limelight','Restricted','The Gamma Collection'),
 (758,'R8 Revolver','Reboot','Restricted','The Gamma Collection'),
 (759,'P90','Chopper','Restricted','The Gamma Collection'),
 (760,'AWP','Phobos','Restricted','The Gamma Collection'),
 (761,'AUG','Aristocrat','Restricted','The Gamma Collection'),
 (762,'Tec-9','Ice Cap','Mil-Spec','The Gamma Collection'),
 (763,'SG 553','Aerial','Mil-Spec','The Gamma Collection'),
 (764,'PP-Bizon','Harvester','Mil-Spec','The Gamma Collection'),
 (765,'P250','Iron Clad','Mil-Spec','The Gamma Collection'),
 (766,'Nova','Exo','Mil-Spec','The Gamma Collection'),
 (767,'MAC-10','Carnivore','Mil-Spec','The Gamma Collection'),
 (768,'Five-SeveN','Violent Daimyo','Mil-Spec','The Gamma Collection'),
 (769,'Bayonet','Lore','Covert','Gamma 2 Case'),
 (770,'Flip Knife','Lore','Covert','Gamma 2 Case'),
 (771,'Gut Knife','Lore','Covert','Gamma 2 Case'),
 (772,'Karambit','Lore','Covert','Gamma 2 Case'),
 (773,'M9 Bayonet','Lore','Covert','Gamma 2 Case'),
 (774,'Bayonet','Black Laminate','Covert','Gamma 2 Case'),
 (775,'Flip Knife','Black Laminate','Covert','Gamma 2 Case'),
 (776,'Gut Knife','Black Laminate','Covert','Gamma 2 Case'),
 (777,'Karambit','Black Laminate','Covert','Gamma 2 Case'),
 (778,'M9 Bayonet','Black Laminate','Covert','Gamma 2 Case'),
 (779,'Bayonet','Gamma Doppler','Covert','Gamma 2 Case'),
 (780,'Flip Knife','Gamma Doppler','Covert','Gamma 2 Case'),
 (781,'Gut Knife','Gamma Doppler','Covert','Gamma 2 Case'),
 (782,'Karambit','Gamma Doppler','Covert','Gamma 2 Case'),
 (783,'M9 Bayonet','Gamma Doppler','Covert','Gamma 2 Case'),
 (784,'Bayonet','Autotronic','Covert','Gamma 2 Case'),
 (785,'Flip Knife','Autotronic','Covert','Gamma 2 Case'),
 (786,'Gut Knife','Autotronic','Covert','Gamma 2 Case'),
 (787,'Karambit','Autotronic','Covert','Gamma 2 Case'),
 (788,'M9 Bayonet','Autotronic','Covert','Gamma 2 Case'),
 (789,'Bayonet','Bright Water','Covert','Gamma 2 Case'),
 (790,'Flip Knife','Bright Water','Covert','Gamma 2 Case'),
 (791,'Gut Knife','Bright Water','Covert','Gamma 2 Case'),
 (792,'Karambit','Bright Water','Covert','Gamma 2 Case'),
 (793,'M9 Bayonet','Bright Water','Covert','Gamma 2 Case'),
 (794,'Bayonet','Freehand','Covert','Gamma 2 Case'),
 (795,'Flip Knife','Freehand','Covert','Gamma 2 Case'),
 (796,'Gut Knife','Freehand','Covert','Gamma 2 Case'),
 (797,'Karambit','Freehand','Covert','Gamma 2 Case'),
 (798,'M9 Bayonet','Freehand','Covert','Gamma 2 Case'),
 (799,'AK-47','Neon Revolution','Covert','The Gamma 2 Collection'),
 (800,'AUG','Syd Mead','Classified','The Gamma 2 Collection'),
 (801,'CZ75-Auto','Imprint','Mil-Spec','The Gamma 2 Collection'),
 (802,'Desert Eagle','Directive','Restricted','The Gamma 2 Collection'),
 (803,'FAMAS','Roll Cage','Covert','The Gamma 2 Collection'),
 (804,'Five-SeveN','Scumbria','Mil-Spec','The Gamma 2 Collection'),
 (805,'G3SG1','Ventilator','Mil-Spec','The Gamma 2 Collection'),
 (806,'Glock-18','Weasel','Restricted','The Gamma 2 Collection'),
 (807,'MAG-7','Petroglyph','Restricted','The Gamma 2 Collection'),
 (808,'MP9','Airlock','Classified','The Gamma 2 Collection'),
 (809,'Negev','Dazzle','Mil-Spec','The Gamma 2 Collection'),
 (810,'P90','Grim','Mil-Spec','The Gamma 2 Collection'),
 (811,'SCAR-20','Powercore','Restricted','The Gamma 2 Collection'),
 (812,'SG 553','Triarch','Restricted','The Gamma 2 Collection'),
 (813,'Tec-9','Fuel Injector','Classified','The Gamma 2 Collection'),
 (814,'UMP-45','Briefing','Mil-Spec','The Gamma 2 Collection'),
 (815,'XM1014','Slipstream','Mil-Spec','The Gamma 2 Collection'),
 (816,'CZ75-Auto','Polymer','Mil-Spec','The Glove Collection'),
 (817,'Glock-18','Ironwork','Mil-Spec','The Glove Collection'),
 (818,'MP7','Cirrus','Mil-Spec','The Glove Collection'),
 (819,'Galil AR','Black Sand','Mil-Spec','The Glove Collection'),
 (820,'MP9','Sand Scale','Mil-Spec','The Glove Collection'),
 (821,'MAG-7','Sonar','Mil-Spec','The Glove Collection'),
 (822,'P2000','Turf','Mil-Spec','The Glove Collection'),
 (823,'Dual Berettas','Royal Consorts','Restricted','The Glove Collection'),
 (824,'G3SG1','Stinger','Restricted','The Glove Collection'),
 (825,'M4A1-S','Flashback','Restricted','The Glove Collection'),
 (826,'Nova','Gila','Restricted','The Glove Collection'),
 (827,'USP-S','Cyrex','Restricted','The Glove Collection'),
 (828,'FAMAS','Mecha Industries','Classified','The Glove Collection'),
 (829,'P90','Shallow Grave','Classified','The Glove Collection'),
 (830,'Sawed-Off','Wasteland Princess','Classified','The Glove Collection'),
 (831,'SSG 08','Dragonfire','Covert','The Glove Collection'),
 (832,'M4A4','Buzz Kill','Covert','The Glove Collection'),
 (833,'PP-Bizon','Jungle Slipstream','Mil-Spec','The Spectrum Collection'),
 (834,'SCAR-20','Blueprint','Mil-Spec','The Spectrum Collection'),
 (835,'Desert Eagle','Oxide Blaze','Mil-Spec','The Spectrum Collection'),
 (836,'Five-SeveN','Capillary','Mil-Spec','The Spectrum Collection'),
 (837,'MP7','Akoben','Mil-Spec','The Spectrum Collection'),
 (838,'P250','Ripple','Mil-Spec','The Spectrum Collection'),
 (839,'Sawed-Off','Zander','Mil-Spec','The Spectrum Collection'),
 (840,'Galil AR','Crimson Tsunami','Restricted','The Spectrum Collection'),
 (841,'M249','Emerald Poison Dart','Restricted','The Spectrum Collection'),
 (842,'MAC-10','Last Dive','Restricted','The Spectrum Collection'),
 (843,'UMP-45','Scaffold','Restricted','The Spectrum Collection'),
 (844,'XM1014','Seasons','Restricted','The Spectrum Collection'),
 (845,'AWP','Fever Dream','Classified','The Spectrum Collection'),
 (846,'CZ75-Auto','Xiangliu','Classified','The Spectrum Collection'),
 (847,'M4A1-S','Decimator','Classified','The Spectrum Collection'),
 (848,'AK-47','Bloodsport','Covert','The Spectrum Collection'),
 (849,'USP-S','Neo-Noir','Covert','The Spectrum Collection'),
 (850,'Bowie Knife','Damascus Steel','Covert','Spectrum Case'),
 (851,'Bowie Knife','Doppler','Covert','Spectrum Case'),
 (852,'Bowie Knife','Marble Fade','Covert','Spectrum Case'),
 (853,'Bowie Knife','Tiger Tooth','Covert','Spectrum Case'),
 (854,'Bowie Knife','Rust Coat','Covert','Spectrum Case'),
 (855,'Bowie Knife','Ultraviolet','Covert','Spectrum Case'),
 (856,'Butterfly Knife','Damascus Steel','Covert','Spectrum Case'),
 (857,'Butterfly Knife','Doppler','Covert','Spectrum Case'),
 (858,'Butterfly Knife','Marble Fade','Covert','Spectrum Case'),
 (859,'Butterfly Knife','Tiger Tooth','Covert','Spectrum Case'),
 (860,'Butterfly Knife','Rust Coat','Covert','Spectrum Case'),
 (861,'Butterfly Knife','Ultraviolet','Covert','Spectrum Case'),
 (862,'Falchion Knife','Damascus Steel','Covert','Spectrum Case'),
 (863,'Falchion Knife','Doppler','Covert','Spectrum Case'),
 (864,'Falchion Knife','Marble Fade','Covert','Spectrum Case'),
 (865,'Falchion Knife','Tiger Tooth','Covert','Spectrum Case'),
 (866,'Falchion Knife','Rust Coat','Covert','Spectrum Case'),
 (867,'Falchion Knife','Ultraviolet','Covert','Spectrum Case'),
 (868,'Huntsman Knife','Damascus Steel','Covert','Spectrum Case'),
 (869,'Huntsman Knife','Doppler','Covert','Spectrum Case'),
 (870,'Huntsman Knife','Marble Fade','Covert','Spectrum Case'),
 (871,'Huntsman Knife','Tiger Tooth','Covert','Spectrum Case'),
 (872,'Huntsman Knife','Rust Coat','Covert','Spectrum Case'),
 (873,'Huntsman Knife','Ultraviolet','Covert','Spectrum Case'),
 (874,'Shadow Daggers','Damascus Steel','Covert','Spectrum Case'),
 (875,'Shadow Daggers','Doppler','Covert','Spectrum Case'),
 (876,'Shadow Daggers','Marble Fade','Covert','Spectrum Case'),
 (877,'Shadow Daggers','Tiger Tooth','Covert','Spectrum Case'),
 (878,'Shadow Daggers','Rust Coat','Covert','Spectrum Case'),
 (879,'Shadow Daggers','Ultraviolet','Covert','Spectrum Case'),
 (880,'USP-S','Blueprint','Mil-Spec','The Operation Hydra Collection'),
 (881,'FAMAS','Macabre','Mil-Spec','The Operation Hydra Collection'),
 (882,'M4A1-S','Briefing','Mil-Spec','The Operation Hydra Collection'),
 (883,'MAC-10','Aloha','Mil-Spec','The Operation Hydra Collection'),
 (884,'MAG-7','Hard Water','Mil-Spec','The Operation Hydra Collection'),
 (885,'Tec-9','Cut Out','Mil-Spec','The Operation Hydra Collection'),
 (886,'UMP-45','Metal Flowers','Mil-Spec','The Operation Hydra Collection'),
 (887,'AK-47','Orbit Mk01','Restricted','The Operation Hydra Collection'),
 (888,'P2000','Woodsman','Restricted','The Operation Hydra Collection'),
 (889,'P250','Red Rock','Restricted','The Operation Hydra Collection'),
 (890,'P90','Death Grip','Restricted','The Operation Hydra Collection'),
 (891,'SSG 08','Death''s Head','Restricted','The Operation Hydra Collection'),
 (892,'Dual Berettas','Cobra Strike','Classified','The Operation Hydra Collection'),
 (893,'Galil AR','Sugar Rush','Classified','The Operation Hydra Collection'),
 (894,'M4A4','Hellfire','Classified','The Operation Hydra Collection'),
 (895,'Five-SeveN','Hyper Beast','Covert','The Operation Hydra Collection'),
 (896,'AWP','Oni Taiji','Covert','The Operation Hydra Collection'),
 (897,'Sawed-Off','Morris','Mil-Spec','The Spectrum 2 Collection'),
 (898,'AUG','Triqua','Mil-Spec','The Spectrum 2 Collection'),
 (899,'G3SG1','Hunter','Mil-Spec','The Spectrum 2 Collection'),
 (900,'Glock-18','Off World','Mil-Spec','The Spectrum 2 Collection'),
 (901,'MAC-10','Oceanic','Mil-Spec','The Spectrum 2 Collection'),
 (902,'Tec-9','Cracked Opal','Mil-Spec','The Spectrum 2 Collection'),
 (903,'SCAR-20','Jungle Slipstream','Mil-Spec','The Spectrum 2 Collection'),
 (904,'MP9','Goo','Restricted','The Spectrum 2 Collection'),
 (905,'SG 553','Phantom','Restricted','The Spectrum 2 Collection'),
 (906,'CZ75-Auto','Tacticat','Restricted','The Spectrum 2 Collection'),
 (907,'UMP-45','Exposure','Restricted','The Spectrum 2 Collection'),
 (908,'XM1014','Ziggy','Restricted','The Spectrum 2 Collection'),
 (909,'PP-Bizon','High Roller','Classified','The Spectrum 2 Collection'),
 (910,'M4A1-S','Leaded Glass','Classified','The Spectrum 2 Collection'),
 (911,'R8 Revolver','Llama Cannon','Classified','The Spectrum 2 Collection'),
 (912,'AK-47','The Empress','Covert','The Spectrum 2 Collection'),
 (913,'P250','See Ya Later','Covert','The Spectrum 2 Collection'),
 (914,'PP-Bizon','Night Riot','Mil-Spec','The Clutch Collection'),
 (915,'Five-SeveN','Flame Test','Mil-Spec','The Clutch Collection'),
 (916,'MP9','Black Sand','Mil-Spec','The Clutch Collection'),
 (917,'P2000','Urban Hazard','Mil-Spec','The Clutch Collection'),
 (918,'R8 Revolver','Grip','Mil-Spec','The Clutch Collection'),
 (919,'SG 553','Aloha','Mil-Spec','The Clutch Collection'),
 (920,'XM1014','Oxide Blaze','Mil-Spec','The Clutch Collection'),
 (921,'Glock-18','Moonrise','Restricted','The Clutch Collection'),
 (922,'Negev','Lionfish','Restricted','The Clutch Collection'),
 (923,'Nova','Wild Six','Restricted','The Clutch Collection'),
 (924,'MAG-7','SWAG-7','Restricted','The Clutch Collection'),
 (925,'UMP-45','Arctic Wolf','Restricted','The Clutch Collection'),
 (926,'AUG','Stymphalian','Classified','The Clutch Collection'),
 (927,'AWP','Mortis','Classified','The Clutch Collection'),
 (928,'USP-S','Cortex','Classified','The Clutch Collection'),
 (929,'M4A4','Neo-Noir','Covert','The Clutch Collection'),
 (930,'MP7','Bloodsport','Covert','The Clutch Collection'),
 (931,'AUG','Amber Slipstream','Mil-Spec','The Horizon Collection'),
 (932,'Dual Berettas','Shred','Mil-Spec','The Horizon Collection'),
 (933,'Glock-18','Warhawk','Mil-Spec','The Horizon Collection'),
 (934,'MP9','Capillary','Mil-Spec','The Horizon Collection'),
 (935,'P90','Traction','Mil-Spec','The Horizon Collection'),
 (936,'R8 Revolver','Survivalist','Mil-Spec','The Horizon Collection'),
 (937,'Tec-9','Snek-9','Mil-Spec','The Horizon Collection'),
 (938,'CZ75-Auto','Eco','Restricted','The Horizon Collection'),
 (939,'G3SG1','High Seas','Restricted','The Horizon Collection'),
 (940,'Nova','Toy Soldier','Restricted','The Horizon Collection'),
 (941,'AWP','PAW','Restricted','The Horizon Collection'),
 (942,'MP7','Powercore','Restricted','The Horizon Collection'),
 (943,'M4A1-S','Nightmare','Classified','The Horizon Collection'),
 (944,'Sawed-Off','Devourer','Classified','The Horizon Collection'),
 (945,'FAMAS','Eye of Athena','Classified','The Horizon Collection'),
 (946,'AK-47','Neon Rider','Covert','The Horizon Collection'),
 (947,'Desert Eagle','Code Red','Covert','The Horizon Collection'),
 (948,'Stiletto Knife','★ (Vanilla)','Covert','Horizon Case'),
 (949,'Stiletto Knife','Blue Steel','Covert','Horizon Case'),
 (950,'Stiletto Knife','Boreal Forest','Covert','Horizon Case'),
 (951,'Stiletto Knife','Case Hardened','Covert','Horizon Case'),
 (952,'Stiletto Knife','Crimson Web','Covert','Horizon Case'),
 (953,'Stiletto Knife','Fade','Covert','Horizon Case'),
 (954,'Stiletto Knife','Forest DDPAT','Covert','Horizon Case'),
 (955,'Stiletto Knife','Night Stripe','Covert','Horizon Case'),
 (956,'Stiletto Knife','Safari Mesh','Covert','Horizon Case'),
 (957,'Stiletto Knife','Scorched','Covert','Horizon Case'),
 (958,'Stiletto Knife','Slaughter','Covert','Horizon Case'),
 (959,'Stiletto Knife','Stained','Covert','Horizon Case'),
 (960,'Stiletto Knife','Urban Masked','Covert','Horizon Case'),
 (961,'Ursus Knife','★ (Vanilla)','Covert','Horizon Case'),
 (962,'Ursus Knife','Blue Steel','Covert','Horizon Case'),
 (963,'Ursus Knife','Boreal Forest','Covert','Horizon Case'),
 (964,'Ursus Knife','Case Hardened','Covert','Horizon Case'),
 (965,'Ursus Knife','Crimson Web','Covert','Horizon Case'),
 (966,'Ursus Knife','Fade','Covert','Horizon Case'),
 (967,'Ursus Knife','Forest DDPAT','Covert','Horizon Case'),
 (968,'Ursus Knife','Night Stripe','Covert','Horizon Case'),
 (969,'Ursus Knife','Safari Mesh','Covert','Horizon Case'),
 (970,'Ursus Knife','Scorched','Covert','Horizon Case'),
 (971,'Ursus Knife','Slaughter','Covert','Horizon Case'),
 (972,'Ursus Knife','Stained','Covert','Horizon Case'),
 (973,'Ursus Knife','Urban Masked','Covert','Horizon Case'),
 (974,'Navaja Knife','★ (Vanilla)','Covert','Horizon Case'),
 (975,'Navaja Knife','Blue Steel','Covert','Horizon Case'),
 (976,'Navaja Knife','Boreal Forest','Covert','Horizon Case'),
 (977,'Navaja Knife','Case Hardened','Covert','Horizon Case'),
 (978,'Navaja Knife','Crimson Web','Covert','Horizon Case'),
 (979,'Navaja Knife','Fade','Covert','Horizon Case'),
 (980,'Navaja Knife','Forest DDPAT','Covert','Horizon Case'),
 (981,'Navaja Knife','Night Stripe','Covert','Horizon Case'),
 (982,'Navaja Knife','Safari Mesh','Covert','Horizon Case'),
 (983,'Navaja Knife','Scorched','Covert','Horizon Case'),
 (984,'Navaja Knife','Slaughter','Covert','Horizon Case'),
 (985,'Navaja Knife','Stained','Covert','Horizon Case'),
 (986,'Navaja Knife','Urban Masked','Covert','Horizon Case'),
 (987,'Talon Knife','★ (Vanilla)','Covert','Horizon Case'),
 (988,'Talon Knife','Blue Steel','Covert','Horizon Case'),
 (989,'Talon Knife','Boreal Forest','Covert','Horizon Case'),
 (990,'Talon Knife','Case Hardened','Covert','Horizon Case'),
 (991,'Talon Knife','Crimson Web','Covert','Horizon Case'),
 (992,'Talon Knife','Fade','Covert','Horizon Case'),
 (993,'Talon Knife','Forest DDPAT','Covert','Horizon Case'),
 (994,'Talon Knife','Night Stripe','Covert','Horizon Case'),
 (995,'Talon Knife','Safari Mesh','Covert','Horizon Case'),
 (996,'Talon Knife','Scorched','Covert','Horizon Case'),
 (997,'Talon Knife','Slaughter','Covert','Horizon Case'),
 (998,'Talon Knife','Stained','Covert','Horizon Case'),
 (999,'Talon Knife','Urban Masked','Covert','Horizon Case'),
 (1000,'PP-Bizon','Facility Sketch','Consumer','The 2018 Nuke Collection'),
 (1001,'P250','Facility Draft','Consumer','The 2018 Nuke Collection'),
 (1002,'UMP-45','Facility Dark','Consumer','The 2018 Nuke Collection'),
 (1003,'Five-SeveN','Coolant','Consumer','The 2018 Nuke Collection'),
 (1004,'Nova','Mandrel','Consumer','The 2018 Nuke Collection'),
 (1005,'M4A4','Mainframe','Industrial','The 2018 Nuke Collection'),
 (1006,'MP7','Motherboard','Industrial','The 2018 Nuke Collection'),
 (1007,'Negev','Bulkhead','Industrial','The 2018 Nuke Collection'),
 (1008,'Galil AR','Cold Fusion','Industrial','The 2018 Nuke Collection'),
 (1009,'P90','Facility Negative','Mil-Spec','The 2018 Nuke Collection'),
 (1010,'MP5-SD','Co-Processor','Mil-Spec','The 2018 Nuke Collection'),
 (1011,'P250','Exchanger','Mil-Spec','The 2018 Nuke Collection'),
 (1012,'AWP','Acheron','Mil-Spec','The 2018 Nuke Collection'),
 (1013,'AUG','Random Access','Restricted','The 2018 Nuke Collection'),
 (1014,'MAG-7','Core Breach','Restricted','The 2018 Nuke Collection'),
 (1015,'Glock-18','Nuclear Garden','Restricted','The 2018 Nuke Collection'),
 (1016,'Tec-9','Remote Control','Classified','The 2018 Nuke Collection'),
 (1017,'M4A1-S','Control Panel','Classified','The 2018 Nuke Collection'),
 (1018,'UMP-45','Mudder','Consumer','The 2018 Inferno Collection'),
 (1019,'MP5-SD','Dirt Drop','Consumer','The 2018 Inferno Collection'),
 (1020,'MP9','Slide','Consumer','The 2018 Inferno Collection'),
 (1021,'AUG','Sweeper','Consumer','The 2018 Inferno Collection'),
 (1022,'MAG-7','Rust Coat','Consumer','The 2018 Inferno Collection'),
 (1023,'PP-Bizon','Candy Apple','Industrial','The 2018 Inferno Collection'),
 (1024,'MAC-10','Calf Skin','Industrial','The 2018 Inferno Collection'),
 (1025,'R8 Revolver','Nitro','Industrial','The 2018 Inferno Collection'),
 (1026,'Glock-18','High Beam','Industrial','The 2018 Inferno Collection'),
 (1027,'SSG 08','Hand Brake','Mil-Spec','The 2018 Inferno Collection'),
 (1028,'M4A4','Converter','Mil-Spec','The 2018 Inferno Collection'),
 (1029,'USP-S','Check Engine','Mil-Spec','The 2018 Inferno Collection'),
 (1030,'Sawed-Off','Brake Light','Mil-Spec','The 2018 Inferno Collection'),
 (1031,'P250','Vino Primo','Restricted','The 2018 Inferno Collection'),
 (1032,'MP7','Fade','Restricted','The 2018 Inferno Collection'),
 (1033,'AK-47','Safety Net','Restricted','The 2018 Inferno Collection'),
 (1034,'Dual Berettas','Twin Turbo','Classified','The 2018 Inferno Collection'),
 (1035,'SG 553','Integrale','Classified','The 2018 Inferno Collection'),
 (1036,'MP5-SD','Lab Rats','Restricted','The Blacksite Collection'),
 (1037,'MP9','Modest Threat','Mil-Spec','The Danger Zone Collection'),
 (1038,'Glock-18','Oxide Blaze','Mil-Spec','The Danger Zone Collection'),
 (1039,'Nova','Wood Fired','Mil-Spec','The Danger Zone Collection'),
 (1040,'M4A4','Magnesium','Mil-Spec','The Danger Zone Collection'),
 (1041,'Sawed-Off','Black Sand','Mil-Spec','The Danger Zone Collection'),
 (1042,'SG 553','Danger Close','Mil-Spec','The Danger Zone Collection'),
 (1043,'Tec-9','Fubar','Mil-Spec','The Danger Zone Collection'),
 (1044,'G3SG1','Scavenger','Restricted','The Danger Zone Collection'),
 (1045,'Galil AR','Signal','Restricted','The Danger Zone Collection'),
 (1046,'MAC-10','Pipe Down','Restricted','The Danger Zone Collection'),
 (1047,'P250','Nevermore','Restricted','The Danger Zone Collection'),
 (1048,'USP-S','Flashback','Restricted','The Danger Zone Collection'),
 (1049,'UMP-45','Momentum','Classified','The Danger Zone Collection'),
 (1050,'Desert Eagle','Mecha Industries','Classified','The Danger Zone Collection'),
 (1051,'MP5-SD','Phosphor','Classified','The Danger Zone Collection'),
 (1052,'AK-47','Asiimov','Covert','The Danger Zone Collection'),
 (1053,'AWP','Neo-Noir','Covert','The Danger Zone Collection'),
 (1056,'FAMAS','Crypsis','Mil-Spec','The Prisma Collection'),
 (1057,'AK-47','Uncharted','Mil-Spec','The Prisma Collection'),
 (1058,'MAC-10','Whitefish','Mil-Spec','The Prisma Collection'),
 (1059,'Galil AR','Akoben','Mil-Spec','The Prisma Collection'),
 (1060,'MP7','Mischief','Mil-Spec','The Prisma Collection'),
 (1061,'P250','Verdigris','Mil-Spec','The Prisma Collection'),
 (1062,'P90','Off World','Mil-Spec','The Prisma Collection'),
 (1063,'AWP','Atheris','Restricted','The Prisma Collection'),
 (1064,'Tec-9','Bamboozle','Restricted','The Prisma Collection'),
 (1065,'Desert Eagle','Light Rail','Restricted','The Prisma Collection'),
 (1066,'MP5-SD','Gauss','Restricted','The Prisma Collection'),
 (1067,'UMP-45','Moonrise','Restricted','The Prisma Collection'),
 (1068,'R8 Revolver','Skull Crusher','Classified','The Prisma Collection'),
 (1069,'AUG','Momentum','Classified','The Prisma Collection'),
 (1070,'XM1014','Incinegator','Classified','The Prisma Collection'),
 (1071,'Five-SeveN','Angry Mob','Covert','The Prisma Collection'),
 (1072,'M4A4','The Emperor','Covert','The Prisma Collection'),
 (1073,'Navaja Knife','Damascus Steel','Covert','Prisma Case'),
 (1074,'Navaja Knife','Doppler','Covert','Prisma Case'),
 (1075,'Navaja Knife','Marble Fade','Covert','Prisma Case'),
 (1076,'Navaja Knife','Rust Coat','Covert','Prisma Case'),
 (1077,'Navaja Knife','Tiger Tooth','Covert','Prisma Case'),
 (1078,'Navaja Knife','Ultraviolet','Covert','Prisma Case'),
 (1079,'Stiletto Knife','Damascus Steel','Covert','Prisma Case'),
 (1080,'Stiletto Knife','Doppler','Covert','Prisma Case'),
 (1081,'Stiletto Knife','Marble Fade','Covert','Prisma Case'),
 (1082,'Stiletto Knife','Rust Coat','Covert','Prisma Case'),
 (1083,'Stiletto Knife','Tiger Tooth','Covert','Prisma Case'),
 (1084,'Stiletto Knife','Ultraviolet','Covert','Prisma Case'),
 (1085,'Talon Knife','Damascus Steel','Covert','Prisma Case'),
 (1086,'Talon Knife','Doppler','Covert','Prisma Case'),
 (1087,'Talon Knife','Marble Fade','Covert','Prisma Case'),
 (1088,'Talon Knife','Rust Coat','Covert','Prisma Case'),
 (1089,'Talon Knife','Tiger Tooth','Covert','Prisma Case'),
 (1090,'Talon Knife','Ultraviolet','Covert','Prisma Case'),
 (1091,'Ursus Knife','Damascus Steel','Covert','Prisma Case'),
 (1092,'Ursus Knife','Doppler','Covert','Prisma Case'),
 (1093,'Ursus Knife','Marble Fade','Covert','Prisma Case'),
 (1094,'Ursus Knife','Rust Coat','Covert','Prisma Case'),
 (1095,'Ursus Knife','Tiger Tooth','Covert','Prisma Case'),
 (1096,'Ursus Knife','Ultraviolet','Covert','Prisma Case'),
 (1097,'P250','X-Ray','Restricted','The X-Ray Collection'),
 (1098,'Dual Berettas','Elite 1.6','Mil-Spec','The CS20 Collection'),
 (1099,'Tec-9','Flash Out','Mil-Spec','The CS20 Collection'),
 (1100,'MAC-10','Classic Crate','Mil-Spec','The CS20 Collection'),
 (1101,'MAG-7','Popdog','Mil-Spec','The CS20 Collection'),
 (1102,'SCAR-20','Assault','Mil-Spec','The CS20 Collection'),
 (1103,'FAMAS','Decommissioned','Mil-Spec','The CS20 Collection'),
 (1104,'Glock-18','Sacrifice','Mil-Spec','The CS20 Collection'),
 (1105,'M249','Aztec','Restricted','The CS20 Collection'),
 (1106,'MP5-SD','Agent','Restricted','The CS20 Collection'),
 (1107,'Five-SeveN','Buddy','Restricted','The CS20 Collection'),
 (1108,'P250','Inferno','Restricted','The CS20 Collection'),
 (1109,'UMP-45','Plastique','Restricted','The CS20 Collection'),
 (1110,'MP9','Hydra','Classified','The CS20 Collection'),
 (1111,'P90','Nostalgia','Classified','The CS20 Collection'),
 (1112,'AUG','Death by Puppy','Classified','The CS20 Collection'),
 (1113,'AWP','Wildfire','Covert','The CS20 Collection'),
 (1114,'FAMAS','Commemoration','Covert','The CS20 Collection'),
 (1115,'Classic Knife','★ (Vanilla)','Covert','CS20 Case'),
 (1116,'Classic Knife','Fade','Covert','CS20 Case'),
 (1117,'Classic Knife','Slaughter','Covert','CS20 Case'),
 (1118,'Classic Knife','Blue Steel','Covert','CS20 Case'),
 (1119,'Classic Knife','Stained','Covert','CS20 Case'),
 (1120,'Classic Knife','Case Hardened','Covert','CS20 Case'),
 (1121,'Classic Knife','Forest DDPAT','Covert','CS20 Case'),
 (1122,'Classic Knife','Boreal Forest','Covert','CS20 Case'),
 (1123,'Classic Knife','Crimson Web','Covert','CS20 Case'),
 (1124,'Classic Knife','Scorched','Covert','CS20 Case'),
 (1125,'Classic Knife','Safari Mesh','Covert','CS20 Case'),
 (1126,'Classic Knife','Night Stripe','Covert','CS20 Case'),
 (1127,'Classic Knife','Urban Masked','Covert','CS20 Case'),
 (1128,'MP5-SD','Bamboo Garden','Consumer','The St. Marc Collection'),
 (1129,'MAC-10','Surfwood','Consumer','The St. Marc Collection'),
 (1130,'PP-Bizon','Seabird','Consumer','The St. Marc Collection'),
 (1131,'Sawed-Off','Jungle Thicket','Consumer','The St. Marc Collection'),
 (1132,'M249','Jungle','Consumer','The St. Marc Collection'),
 (1133,'P90','Sunset Lily','Industrial','The St. Marc Collection'),
 (1134,'M4A4','Dark Blossom','Industrial','The St. Marc Collection'),
 (1135,'XM1014','Banana Leaf','Industrial','The St. Marc Collection'),
 (1136,'Tec-9','Rust Leaf','Industrial','The St. Marc Collection'),
 (1137,'UMP-45','Day Lily','Mil-Spec','The St. Marc Collection'),
 (1138,'Five-SeveN','Crimson Blossom','Mil-Spec','The St. Marc Collection'),
 (1139,'MP7','Teal Blossom','Mil-Spec','The St. Marc Collection'),
 (1140,'FAMAS','Sundown','Mil-Spec','The St. Marc Collection'),
 (1141,'SSG 08','Sea Calico','Restricted','The St. Marc Collection'),
 (1142,'Glock-18','Synth Leaf','Restricted','The St. Marc Collection'),
 (1143,'AUG','Midnight Lily','Restricted','The St. Marc Collection'),
 (1144,'MP9','Wild Lily','Classified','The St. Marc Collection'),
 (1145,'AK-47','Wild Lotus','Covert','The St. Marc Collection'),
 (1146,'AUG','Navy Murano','Consumer','The Canals Collection'),
 (1147,'SCAR-20','Stone Mosaico','Consumer','The Canals Collection'),
 (1148,'R8 Revolver','Canal Spray','Consumer','The Canals Collection'),
 (1149,'Negev','Boroque Sand','Consumer','The Canals Collection'),
 (1150,'CZ75-Auto','Indigo','Consumer','The Canals Collection'),
 (1151,'AK-47','Baroque Purple','Industrial','The Canals Collection'),
 (1152,'SG 553','Candy Apple','Industrial','The Canals Collection'),
 (1153,'P250','Dark Filigree','Industrial','The Canals Collection'),
 (1154,'Tec-9','Orange Murano','Industrial','The Canals Collection'),
 (1155,'P90','Baroque Red','Mil-Spec','The Canals Collection'),
 (1156,'G3SG1','Violet Murano','Mil-Spec','The Canals Collection'),
 (1157,'Dual Berettas','Emerald','Mil-Spec','The Canals Collection'),
 (1158,'SSG 08','Orange Filigree','Mil-Spec','The Canals Collection'),
 (1159,'MP9','Stained Glass','Restricted','The Canals Collection'),
 (1160,'MAC-10','Red Filigree','Restricted','The Canals Collection'),
 (1161,'Nova','Baroque Orange','Restricted','The Canals Collection'),
 (1162,'MAG-7','Cinquedea','Classified','The Canals Collection'),
 (1163,'AWP','The Prince','Covert','The Canals Collection'),
 (1164,'SG 553','Barricade','Consumer','The Norse Collection'),
 (1165,'Galil AR','Tornado','Consumer','The Norse Collection'),
 (1166,'MP7','Scorched','Consumer','The Norse Collection'),
 (1167,'SSG 08','Red Stone','Consumer','The Norse Collection'),
 (1168,'FAMAS','Night Borre','Consumer','The Norse Collection'),
 (1169,'M4A1-S','Moss Quartz','Industrial','The Norse Collection'),
 (1171,'MAG-7','Chainmail','Industrial','The Norse Collection'),
 (1172,'Dual Berettas','Pyre','Industrial','The Norse Collection'),
 (1173,'SCAR-20','Brass','Mil-Spec','The Norse Collection'),
 (1174,'CZ75-Auto','Emerald Quartz','Mil-Spec','The Norse Collection'),
 (1175,'XM1014','Frost Borre','Mil-Spec','The Norse Collection'),
 (1176,'MAC-10','Copper Borre','Mil-Spec','The Norse Collection'),
 (1177,'AUG','Flame Jörmungandr','Restricted','The Norse Collection'),
 (1178,'Desert Eagle','Emerald Jörmungandr','Restricted','The Norse Collection'),
 (1179,'P90','Astral Jörmungandr','Restricted','The Norse Collection'),
 (1180,'Negev','Mjölnir','Classified','The Norse Collection'),
 (1181,'AWP','Gungnir','Covert','The Norse Collection'),
 (1182,'MP5-SD','Acid Wash','Mil-Spec','The Shattered Web Collection'),
 (1183,'Nova','Plume','Mil-Spec','The Shattered Web Collection'),
 (1184,'G3SG1','Black Sand','Mil-Spec','The Shattered Web Collection'),
 (1185,'R8 Revolver','Memento','Mil-Spec','The Shattered Web Collection'),
 (1186,'Dual Berettas','Balance','Mil-Spec','The Shattered Web Collection'),
 (1187,'SCAR-20','Torn','Mil-Spec','The Shattered Web Collection'),
 (1188,'M249','Warbird','Mil-Spec','The Shattered Web Collection'),
 (1189,'PP-Bizon','Embargo','Restricted','The Shattered Web Collection'),
 (1190,'AK-47','Rat Rod','Restricted','The Shattered Web Collection'),
 (1191,'AUG','Arctic Wolf','Restricted','The Shattered Web Collection'),
 (1192,'MP7','Neon Ply','Restricted','The Shattered Web Collection'),
 (1193,'P2000','Obsidian','Restricted','The Shattered Web Collection'),
 (1194,'Tec-9','Decimator','Classified','The Shattered Web Collection'),
 (1195,'SG 553','Colony IV','Classified','The Shattered Web Collection'),
 (1196,'SSG 08','Bloodshot','Classified','The Shattered Web Collection'),
 (1197,'AWP','Containment Breach','Covert','The Shattered Web Collection'),
 (1198,'MAC-10','Stalker','Covert','The Shattered Web Collection'),
 (1199,'Nomad Knife','★ (Vanilla)','Covert','Shattered Web Case'),
 (1200,'Nomad Knife','Fade','Covert','Shattered Web Case'),
 (1201,'Nomad Knife','Slaughter','Covert','Shattered Web Case'),
 (1202,'Nomad Knife','Blue Steel','Covert','Shattered Web Case'),
 (1203,'Nomad Knife','Stained','Covert','Shattered Web Case'),
 (1204,'Nomad Knife','Case Hardened','Covert','Shattered Web Case'),
 (1205,'Nomad Knife','Forest DDPAT','Covert','Shattered Web Case'),
 (1206,'Nomad Knife','Boreal Forest','Covert','Shattered Web Case'),
 (1207,'Nomad Knife','Crimson Web','Covert','Shattered Web Case'),
 (1208,'Nomad Knife','Scorched','Covert','Shattered Web Case'),
 (1209,'Nomad Knife','Safari Mesh','Covert','Shattered Web Case'),
 (1210,'Nomad Knife','Night Stripe','Covert','Shattered Web Case'),
 (1211,'Nomad Knife','Urban Masked','Covert','Shattered Web Case'),
 (1212,'Skeleton Knife','★ (Vanilla)','Covert','Shattered Web Case'),
 (1213,'Skeleton Knife','Fade','Covert','Shattered Web Case'),
 (1214,'Skeleton Knife','Slaughter','Covert','Shattered Web Case'),
 (1215,'Skeleton Knife','Blue Steel','Covert','Shattered Web Case'),
 (1216,'Skeleton Knife','Stained','Covert','Shattered Web Case'),
 (1217,'Skeleton Knife','Case Hardened','Covert','Shattered Web Case'),
 (1218,'Skeleton Knife','Forest DDPAT','Covert','Shattered Web Case'),
 (1219,'Skeleton Knife','Boreal Forest','Covert','Shattered Web Case'),
 (1220,'Skeleton Knife','Crimson Web','Covert','Shattered Web Case'),
 (1221,'Skeleton Knife','Scorched','Covert','Shattered Web Case'),
 (1222,'Skeleton Knife','Safari Mesh','Covert','Shattered Web Case'),
 (1223,'Skeleton Knife','Night Stripe','Covert','Shattered Web Case'),
 (1224,'Skeleton Knife','Urban Masked','Covert','Shattered Web Case'),
 (1225,'Survival Knife','★ (Vanilla)','Covert','Shattered Web Case'),
 (1226,'Survival Knife','Fade','Covert','Shattered Web Case'),
 (1227,'Survival Knife','Slaughter','Covert','Shattered Web Case'),
 (1228,'Survival Knife','Blue Steel','Covert','Shattered Web Case'),
 (1229,'Survival Knife','Stained','Covert','Shattered Web Case'),
 (1230,'Survival Knife','Case Hardened','Covert','Shattered Web Case'),
 (1231,'Survival Knife','Forest DDPAT','Covert','Shattered Web Case'),
 (1232,'Survival Knife','Boreal Forest','Covert','Shattered Web Case'),
 (1233,'Survival Knife','Crimson Web','Covert','Shattered Web Case'),
 (1234,'Survival Knife','Scorched','Covert','Shattered Web Case'),
 (1235,'Survival Knife','Safari Mesh','Covert','Shattered Web Case'),
 (1236,'Survival Knife','Night Stripe','Covert','Shattered Web Case'),
 (1237,'Survival Knife','Urban Masked','Covert','Shattered Web Case'),
 (1238,'Paracord Knife','★ (Vanilla)','Covert','Shattered Web Case'),
 (1239,'Paracord Knife','Fade','Covert','Shattered Web Case'),
 (1240,'Paracord Knife','Slaughter','Covert','Shattered Web Case'),
 (1241,'Paracord Knife','Blue Steel','Covert','Shattered Web Case'),
 (1242,'Paracord Knife','Stained','Covert','Shattered Web Case'),
 (1243,'Paracord Knife','Case Hardened','Covert','Shattered Web Case'),
 (1244,'Paracord Knife','Forest DDPAT','Covert','Shattered Web Case'),
 (1245,'Paracord Knife','Boreal Forest','Covert','Shattered Web Case'),
 (1246,'Paracord Knife','Crimson Web','Covert','Shattered Web Case'),
 (1247,'Paracord Knife','Scorched','Covert','Shattered Web Case'),
 (1248,'Paracord Knife','Safari Mesh','Covert','Shattered Web Case'),
 (1249,'Paracord Knife','Night Stripe','Covert','Shattered Web Case'),
 (1250,'Paracord Knife','Urban Masked','Covert','Shattered Web Case'),
 (1251,'AUG','Tom Cat','Mil-Spec','The Prisma 2 Collection'),
 (1252,'AWP','Capillary','Mil-Spec','The Prisma 2 Collection'),
 (1253,'CZ75-Auto','Distressed','Mil-Spec','The Prisma 2 Collection'),
 (1254,'Desert Eagle','Blue Ply','Mil-Spec','The Prisma 2 Collection'),
 (1255,'MP5-SD','Desert Strike','Mil-Spec','The Prisma 2 Collection'),
 (1256,'Negev','Prototype','Mil-Spec','The Prisma 2 Collection'),
 (1257,'R8 Revolver','Bone Forged','Mil-Spec','The Prisma 2 Collection'),
 (1258,'P2000','Acid Etched','Restricted','The Prisma 2 Collection'),
 (1259,'Sawed-Off','Apocalypto','Restricted','The Prisma 2 Collection'),
 (1260,'SCAR-20','Enforcer','Restricted','The Prisma 2 Collection'),
 (1261,'SG 553','Darkwing','Restricted','The Prisma 2 Collection'),
 (1262,'SSG 08','Fever Dream','Restricted','The Prisma 2 Collection'),
 (1263,'AK-47','Phantom Disruptor','Classified','The Prisma 2 Collection'),
 (1264,'MAC-10','Disco Tech','Classified','The Prisma 2 Collection'),
 (1265,'MAG-7','Justice','Classified','The Prisma 2 Collection'),
 (1266,'M4A1-S','Player Two','Covert','The Prisma 2 Collection'),
 (1267,'Glock-18','Bullet Queen','Covert','The Prisma 2 Collection'),
 (1269,'Negev','Ultralight','Mil-Spec','The Fracture Collection'),
 (1270,'P2000','Gnarled','Mil-Spec','The Fracture Collection'),
 (1271,'SG 553','Ol'' Rusty','Mil-Spec','The Fracture Collection'),
 (1272,'SSG 08','Mainframe 001','Mil-Spec','The Fracture Collection'),
 (1273,'P250','Cassette','Mil-Spec','The Fracture Collection'),
 (1274,'P90','Freight','Mil-Spec','The Fracture Collection'),
 (1275,'PP-Bizon','Runic','Mil-Spec','The Fracture Collection'),
 (1276,'MAG-7','Monster Call','Restricted','The Fracture Collection'),
 (1277,'Tec-9','Brother','Restricted','The Fracture Collection'),
 (1278,'MAC-10','Allure','Restricted','The Fracture Collection'),
 (1279,'Galil AR','Connexion','Restricted','The Fracture Collection'),
 (1280,'MP5-SD','Kitbash','Restricted','The Fracture Collection'),
 (1281,'M4A4','Tooth Fairy','Classified','The Fracture Collection'),
 (1282,'Glock-18','Vogue','Classified','The Fracture Collection'),
 (1283,'XM1014','Entombed','Classified','The Fracture Collection'),
 (1284,'Desert Eagle','Printstream','Covert','The Fracture Collection'),
 (1285,'AK-47','Legion of Anubis','Covert','The Fracture Collection'),
 (1286,'CZ75-Auto','Vendetta','Mil-Spec','The Operation Broken Fang Collection'),
 (1287,'P90','Cocoa Rampage','Mil-Spec','The Operation Broken Fang Collection'),
 (1288,'G3SG1','Digital Mesh','Mil-Spec','The Operation Broken Fang Collection'),
 (1289,'Galil AR','Vandal','Mil-Spec','The Operation Broken Fang Collection'),
 (1290,'P250','Contaminant','Mil-Spec','The Operation Broken Fang Collection'),
 (1291,'M249','Deep Relief','Mil-Spec','The Operation Broken Fang Collection'),
 (1292,'MP5-SD','Condition Zero','Mil-Spec','The Operation Broken Fang Collection'),
 (1293,'AWP','Exoskeleton','Restricted','The Operation Broken Fang Collection'),
 (1294,'Dual Berettas','Dezastre','Restricted','The Operation Broken Fang Collection'),
 (1295,'Nova','Clear Polymer','Restricted','The Operation Broken Fang Collection'),
 (1296,'SSG 08','Parallax','Restricted','The Operation Broken Fang Collection'),
 (1297,'UMP-45','Gold Bismuth','Restricted','The Operation Broken Fang Collection'),
 (1298,'Five-SeveN','Fairy Tale','Classified','The Operation Broken Fang Collection'),
 (1299,'M4A4','Cyber Security','Classified','The Operation Broken Fang Collection'),
 (1300,'USP-S','Monster Mashup','Classified','The Operation Broken Fang Collection'),
 (1301,'M4A1-S','Printstream','Covert','The Operation Broken Fang Collection'),
 (1302,'Glock-18','Neo-Noir','Covert','The Operation Broken Fang Collection'),
 (1303,'XM1014','Charter','Consumer','The Control Collection'),
 (1304,'AUG','Surveillance','Consumer','The Control Collection'),
 (1305,'MP9','Army Sheen','Consumer','The Control Collection'),
 (1306,'P250','Forest Night','Consumer','The Control Collection'),
 (1307,'CZ75-Auto','Jungle Dashed','Consumer','The Control Collection'),
 (1308,'Desert Eagle','The Bronze','Industrial','The Control Collection'),
 (1309,'Dual Berettas','Switch Board','Industrial','The Control Collection'),
 (1310,'MP5-SD','Nitro','Industrial','The Control Collection'),
 (1311,'MAG-7','Carbon Fiber','Industrial','The Control Collection'),
 (1312,'M4A4','Global Offensive','Mil-Spec','The Control Collection'),
 (1313,'SSG 08','Threat Detected','Mil-Spec','The Control Collection'),
 (1314,'P2000','Dispatch','Mil-Spec','The Control Collection'),
 (1315,'SCAR-20','Magna Carta','Mil-Spec','The Control Collection'),
 (1316,'FAMAS','Prime Conspiracy','Restricted','The Control Collection'),
 (1317,'Five-SeveN','Berries And Cherries','Restricted','The Control Collection'),
 (1318,'UMP-45','Crime Scene','Restricted','The Control Collection'),
 (1319,'USP-S','Target Acquired','Classified','The Control Collection'),
 (1320,'M4A1-S','Blue Phosphor','Classified','The Control Collection'),
 (1321,'AWP','Fade','Covert','The Control Collection'),
 (1322,'Dual Berettas','Heist','Consumer','The Havoc Collection'),
 (1323,'Tec-9','Phoenix Chalk','Consumer','The Havoc Collection'),
 (1324,'Sawed-Off','Clay Ambush','Consumer','The Havoc Collection'),
 (1325,'PP-Bizon','Death Rattle','Consumer','The Havoc Collection'),
 (1326,'M249','Predator','Consumer','The Havoc Collection'),
 (1327,'MP7','Vault Heist','Industrial','The Havoc Collection'),
 (1328,'UMP-45','Houndstooth','Industrial','The Havoc Collection'),
 (1329,'R8 Revolver','Phoenix Marker','Industrial','The Havoc Collection'),
 (1330,'Nova','Rust Coat','Industrial','The Havoc Collection'),
 (1331,'Desert Eagle','Night Heist','Mil-Spec','The Havoc Collection'),
 (1332,'Negev','Phoenix Stencil','Mil-Spec','The Havoc Collection'),
 (1333,'P90','Tiger Pit','Mil-Spec','The Havoc Collection'),
 (1334,'P250','Bengal Tiger','Mil-Spec','The Havoc Collection'),
 (1335,'Galil AR','Phoenix Blacklight','Restricted','The Havoc Collection'),
 (1336,'SG 553','Hypnotic','Restricted','The Havoc Collection'),
 (1337,'Glock-18','Franklin','Restricted','The Havoc Collection'),
 (1338,'AWP','Silk Tiger','Classified','The Havoc Collection'),
 (1339,'MAC-10','Hot Snakes','Classified','The Havoc Collection'),
 (1340,'AK-47','X-Ray','Covert','The Havoc Collection'),
 (1341,'P90','Ancient Earth','Consumer','The Ancient Collection'),
 (1342,'SG 553','Lush Ruins','Consumer','The Ancient Collection'),
 (1343,'Nova','Army Sheen','Consumer','The Ancient Collection'),
 (1344,'SSG 08','Jungle Dashed','Consumer','The Ancient Collection'),
 (1345,'R8 Revolver','Night','Consumer','The Ancient Collection'),
 (1346,'P2000','Panther Camo','Industrial','The Ancient Collection'),
 (1347,'MP7','Tall Grass','Industrial','The Ancient Collection'),
 (1348,'G3SG1','Ancient Ritual','Industrial','The Ancient Collection'),
 (1349,'CZ75-Auto','Silver','Industrial','The Ancient Collection'),
 (1350,'Tec-9','Blast From the Past','Mil-Spec','The Ancient Collection'),
 (1351,'AUG','Carved Jade','Mil-Spec','The Ancient Collection'),
 (1352,'Galil AR','Dusk Ruins','Mil-Spec','The Ancient Collection'),
 (1353,'FAMAS','Dark Water','Mil-Spec','The Ancient Collection'),
 (1354,'XM1014','Ancient Lore','Restricted','The Ancient Collection'),
 (1355,'MAC-10','Gold Brick','Restricted','The Ancient Collection'),
 (1356,'USP-S','Ancient Visions','Restricted','The Ancient Collection'),
 (1357,'P90','Run and Hide','Classified','The Ancient Collection'),
 (1358,'AK-47','Panthera onca','Classified','The Ancient Collection'),
 (1359,'M4A1-S','Welcome to the Jungle','Covert','The Ancient Collection'),
 (1361,'Glock-18','Clear Polymer','Mil-Spec','The Snakebite Collection'),
 (1362,'M249','O.S.I.P.R.','Mil-Spec','The Snakebite Collection'),
 (1363,'SG 553','Heavy Metal','Mil-Spec','The Snakebite Collection'),
 (1364,'R8 Revolver','Junk Yard','Mil-Spec','The Snakebite Collection'),
 (1365,'UMP-45','Oscillator','Mil-Spec','The Snakebite Collection'),
 (1366,'Nova','Windblown','Mil-Spec','The Snakebite Collection'),
 (1367,'CZ75-Auto','Circaetus','Mil-Spec','The Snakebite Collection'),
 (1368,'AK-47','Slate','Restricted','The Snakebite Collection'),
 (1369,'P250','Cyber Shell','Restricted','The Snakebite Collection'),
 (1370,'Negev','dev_texture','Restricted','The Snakebite Collection'),
 (1371,'MAC-10','Button Masher','Restricted','The Snakebite Collection'),
 (1372,'Desert Eagle','Trigger Discipline','Restricted','The Snakebite Collection'),
 (1373,'MP9','Food Chain','Classified','The Snakebite Collection'),
 (1374,'XM1014','XOXO','Classified','The Snakebite Collection'),
 (1375,'Galil AR','Chromatic Aberration','Classified','The Snakebite Collection'),
 (1376,'USP-S','The Traitor','Covert','The Snakebite Collection'),
 (1377,'M4A4','In Living Color','Covert','The Snakebite Collection'),
 (1379,'R8 Revolver','Desert Brush','Consumer','The 2021 Dust 2 Collection'),
 (1380,'P90','Desert DDPAT','Consumer','The 2021 Dust 2 Collection'),
 (1381,'SG 553','Bleached','Consumer','The 2021 Dust 2 Collection'),
 (1382,'MP7','Prey','Consumer','The 2021 Dust 2 Collection'),
 (1383,'Sawed-Off','Parched','Consumer','The 2021 Dust 2 Collection'),
 (1384,'AUG','Spalted Wood','Industrial','The 2021 Dust 2 Collection'),
 (1385,'MP9','Old Roots','Industrial','The 2021 Dust 2 Collection'),
 (1386,'Five-SeveN','Withered Vine','Industrial','The 2021 Dust 2 Collection'),
 (1387,'M249','Midnight Palm','Industrial','The 2021 Dust 2 Collection'),
 (1388,'P250','Black & Tan','Mil-Spec','The 2021 Dust 2 Collection'),
 (1389,'Nova','Quick Sand','Mil-Spec','The 2021 Dust 2 Collection'),
 (1390,'G3SG1','New Roots','Mil-Spec','The 2021 Dust 2 Collection'),
 (1391,'Galil AR','Amber Fade','Mil-Spec','The 2021 Dust 2 Collection'),
 (1392,'USP-S','Orange Anolis','Restricted','The 2021 Dust 2 Collection'),
 (1393,'M4A4','Red DDPAT','Restricted','The 2021 Dust 2 Collection'),
 (1394,'MAC-10','Case Hardened','Restricted','The 2021 Dust 2 Collection'),
 (1395,'UMP-45','Fade','Classified','The 2021 Dust 2 Collection'),
 (1396,'SSG 08','Death Strike','Classified','The 2021 Dust 2 Collection'),
 (1397,'AK-47','Gold Arabesque','Covert','The 2021 Dust 2 Collection'),
 (1398,'P250','Drought','Consumer','The 2021 Mirage Collection'),
 (1399,'PP-Bizon','Anolis','Consumer','The 2021 Mirage Collection'),
 (1400,'MAG-7','Navy Sheen','Consumer','The 2021 Mirage Collection'),
 (1401,'MAC-10','Sienna Damask','Consumer','The 2021 Mirage Collection'),
 (1402,'SSG 08','Prey','Consumer','The 2021 Mirage Collection'),
 (1403,'Dual Berettas','Drift Wood','Industrial','The 2021 Mirage Collection'),
 (1404,'FAMAS','CaliCamo','Industrial','The 2021 Mirage Collection'),
 (1405,'CZ75-Auto','Midnight Palm','Industrial','The 2021 Mirage Collection'),
 (1406,'P90','Verdant Growth','Industrial','The 2021 Mirage Collection'),
 (1407,'USP-S','Purple DDPAT','Mil-Spec','The 2021 Mirage Collection'),
 (1408,'MP9','Music Box','Mil-Spec','The 2021 Mirage Collection'),
 (1409,'M249','Humidor','Mil-Spec','The 2021 Mirage Collection'),
 (1410,'SG 553','Desert Blossom','Mil-Spec','The 2021 Mirage Collection'),
 (1411,'XM1014','Elegant Vines','Restricted','The 2021 Mirage Collection'),
 (1412,'Glock-18','Pink DDPAT','Restricted','The 2021 Mirage Collection'),
 (1413,'AUG','Sand Storm','Restricted','The 2021 Mirage Collection'),
 (1414,'MP5-SD','Oxide Oasis','Classified','The 2021 Mirage Collection'),
 (1415,'Desert Eagle','Fennec Fox','Classified','The 2021 Mirage Collection'),
 (1416,'AWP','Desert Hydra','Covert','The 2021 Mirage Collection'),
 (1417,'Desert Eagle','Sputnik','Mil-Spec','The 2021 Train Collection'),
 (1418,'M4A1-S','Fizzy POP','Mil-Spec','The 2021 Train Collection'),
 (1419,'SSG 08','Spring Twilly','Mil-Spec','The 2021 Train Collection'),
 (1420,'AUG','Amber Fade','Mil-Spec','The 2021 Train Collection'),
 (1421,'UMP-45','Full Stop','Mil-Spec','The 2021 Train Collection'),
 (1422,'Tec-9','Safety Net','Mil-Spec','The 2021 Train Collection'),
 (1423,'R8 Revolver','Blaze','Mil-Spec','The 2021 Train Collection'),
 (1424,'CZ75-Auto','Syndicate','Restricted','The 2021 Train Collection'),
 (1425,'AWP','POP AWP','Restricted','The 2021 Train Collection'),
 (1426,'P2000','Space Race','Restricted','The 2021 Train Collection'),
 (1427,'MP5-SD','Autumn Twilly','Restricted','The 2021 Train Collection'),
 (1428,'Nova','Red Quartz','Restricted','The 2021 Train Collection'),
 (1429,'FAMAS','Meltdown','Classified','The 2021 Train Collection'),
 (1430,'MAC-10','Propaganda','Classified','The 2021 Train Collection'),
 (1431,'USP-S','Whiteout','Classified','The 2021 Train Collection'),
 (1432,'Glock-18','Gamma Doppler','Covert','The 2021 Train Collection'),
 (1433,'M4A4','The Coalition','Covert','The 2021 Train Collection'),
 (1434,'MAC-10','Strats','Consumer','The 2021 Vertigo Collection'),
 (1435,'FAMAS','Faulty Wiring','Consumer','The 2021 Vertigo Collection'),
 (1436,'XM1014','Blue Tire','Consumer','The 2021 Vertigo Collection'),
 (1437,'CZ75-Auto','Framework','Consumer','The 2021 Vertigo Collection'),
 (1438,'Dual Berettas','Oil Change','Consumer','The 2021 Vertigo Collection'),
 (1439,'Glock-18','Red Tire','Industrial','The 2021 Vertigo Collection'),
 (1440,'UMP-45','Mechanism','Industrial','The 2021 Vertigo Collection'),
 (1441,'SSG 08','Carbon Fiber','Industrial','The 2021 Vertigo Collection'),
 (1442,'PP-Bizon','Breaker Box','Industrial','The 2021 Vertigo Collection'),
 (1443,'AK-47','Green Laminate','Mil-Spec','The 2021 Vertigo Collection'),
 (1444,'P90','Schematic','Mil-Spec','The 2021 Vertigo Collection'),
 (1445,'Nova','Interlock','Mil-Spec','The 2021 Vertigo Collection'),
 (1446,'Negev','Infrastructure','Mil-Spec','The 2021 Vertigo Collection'),
 (1447,'Galil AR','CAUTION!','Restricted','The 2021 Vertigo Collection'),
 (1448,'MAG-7','Prism Terrace','Restricted','The 2021 Vertigo Collection'),
 (1449,'P250','Digital Architect','Restricted','The 2021 Vertigo Collection'),
 (1450,'Five-SeveN','Fall Hazard','Classified','The 2021 Vertigo Collection'),
 (1451,'SG 553','Hazard Pay','Classified','The 2021 Vertigo Collection'),
 (1452,'M4A1-S','Imminent Danger','Covert','The 2021 Vertigo Collection'),
 (1453,'AUG','Plague','Mil-Spec','The Operation Riptide Collection'),
 (1454,'Dual Berettas','Tread','Mil-Spec','The Operation Riptide Collection'),
 (1455,'G3SG1','Keeping Tabs','Mil-Spec','The Operation Riptide Collection'),
 (1456,'MP7','Guerrilla','Mil-Spec','The Operation Riptide Collection'),
 (1457,'PP-Bizon','Lumen','Mil-Spec','The Operation Riptide Collection'),
 (1458,'USP-S','Black Lotus','Mil-Spec','The Operation Riptide Collection'),
 (1459,'XM1014','Watchdog','Mil-Spec','The Operation Riptide Collection'),
 (1460,'MAG-7','BI83 Spectrum','Restricted','The Operation Riptide Collection'),
 (1461,'FAMAS','ZX Spectron','Restricted','The Operation Riptide Collection'),
 (1462,'Five-SeveN','Boost Protocol','Restricted','The Operation Riptide Collection'),
 (1463,'MP9','Mount Fuji','Restricted','The Operation Riptide Collection'),
 (1464,'M4A4','Spider Lily','Restricted','The Operation Riptide Collection'),
 (1465,'MAC-10','Toybox','Classified','The Operation Riptide Collection'),
 (1466,'Glock-18','Snack Attack','Classified','The Operation Riptide Collection'),
 (1467,'SSG 08','Turbo Peek','Classified','The Operation Riptide Collection'),
 (1468,'Desert Eagle','Ocean Drive','Covert','The Operation Riptide Collection'),
 (1469,'AK-47','Leet Museo','Covert','The Operation Riptide Collection'),
 (1470,'Bowie Knife','Gamma Doppler','Covert','Operation Riptide Case'),
 (1471,'Bowie Knife','Freehand','Covert','Operation Riptide Case'),
 (1472,'Bowie Knife','Lore','Covert','Operation Riptide Case'),
 (1473,'Bowie Knife','Autotronic','Covert','Operation Riptide Case'),
 (1474,'Bowie Knife','Black Laminate','Covert','Operation Riptide Case'),
 (1475,'Bowie Knife','Bright Water','Covert','Operation Riptide Case'),
 (1476,'Butterfly Knife','Gamma Doppler','Covert','Operation Riptide Case'),
 (1477,'Butterfly Knife','Freehand','Covert','Operation Riptide Case'),
 (1478,'Butterfly Knife','Lore','Covert','Operation Riptide Case'),
 (1479,'Butterfly Knife','Autotronic','Covert','Operation Riptide Case'),
 (1480,'Butterfly Knife','Black Laminate','Covert','Operation Riptide Case'),
 (1481,'Butterfly Knife','Bright Water','Covert','Operation Riptide Case'),
 (1482,'Falchion Knife','Gamma Doppler','Covert','Operation Riptide Case'),
 (1483,'Falchion Knife','Freehand','Covert','Operation Riptide Case'),
 (1484,'Falchion Knife','Lore','Covert','Operation Riptide Case'),
 (1485,'Falchion Knife','Autotronic','Covert','Operation Riptide Case'),
 (1486,'Falchion Knife','Black Laminate','Covert','Operation Riptide Case'),
 (1487,'Falchion Knife','Bright Water','Covert','Operation Riptide Case'),
 (1488,'Huntsman Knife','Gamma Doppler','Covert','Operation Riptide Case'),
 (1489,'Huntsman Knife','Freehand','Covert','Operation Riptide Case'),
 (1490,'Huntsman Knife','Lore','Covert','Operation Riptide Case'),
 (1491,'Huntsman Knife','Autotronic','Covert','Operation Riptide Case'),
 (1492,'Huntsman Knife','Black Laminate','Covert','Operation Riptide Case'),
 (1493,'Huntsman Knife','Bright Water','Covert','Operation Riptide Case'),
 (1494,'Shadow Daggers','Gamma Doppler','Covert','Operation Riptide Case'),
 (1495,'Shadow Daggers','Freehand','Covert','Operation Riptide Case'),
 (1496,'Shadow Daggers','Lore','Covert','Operation Riptide Case'),
 (1497,'Shadow Daggers','Autotronic','Covert','Operation Riptide Case'),
 (1498,'Shadow Daggers','Black Laminate','Covert','Operation Riptide Case'),
 (1499,'Shadow Daggers','Bright Water','Covert','Operation Riptide Case');
INSERT INTO "Conditions" ("condition_id","condition") VALUES (0,'Factory New'),
 (1,'Minimal Wear'),
 (2,'Field-Tested'),
 (3,'Well-Worn'),
 (4,'Battle-Scarred'),
 (5,'StatTrak Factory New'),
 (6,'StatTrak Minimal Wear'),
 (7,'StatTrak Field-Tested'),
 (8,'StatTrak Well-Worn'),
 (9,'StatTrak Battle-Scarred'),
 (10,'Souvenir Factory New'),
 (11,'Souvenir Minimal Wear'),
 (12,'Souvenir Field-Tested'),
 (13,'Souvenir Well-Worn'),
 (14,'Souvenir Battle-Scarred');
CREATE INDEX IF NOT EXISTS "skin_name" ON "Skins" (
	"Name"
);
CREATE INDEX IF NOT EXISTS "stash_id" ON "Skins" (
	"CSGOStash_ID"
);
COMMIT;
